### ISSUE TITLE
import.meta.resolve for files

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#1008]
You can use `import.meta.resolve` for JavaScript modules, but it’s not currently supported for files (as it assumes that the referenced file is in `_import` rather than `_file`). It would be nice as an alternative to `FileAttachment(name).url()` because it is synchronous, e.g.,

```js
fetch(import.meta.resolve("./data/nyc-taxi.parquet"))
```

Related #954. Perhaps `_import` and `_file` could be combined? But the challenge there is we transpile JavaScript, and hence we want to keep `_import` and `_file` separate. 🤔

**Comment by Fil** [comment]
We can also use `FileAttachment(name).href` for synchronous resolution, but it's good to have both, especially since `import.meta.resolve` is a built-in function.
