### ISSUE TITLE
DuckDBClient doesn't materialize query results and this breaks PIVOT operations (maybe other operations too?)

### ISSUE THREAD

**Issue by mskullcap** [observablehq/framework#1016]
If I attempt to PIVOT ON and do not use an IN clause, DuckDB throws the error:

Error: Invalid Error: PendingQuery can only take a single statement

This file illustrates the problem:
[events.md](https://github.com/observablehq/framework/files/14529864/events.md)

If I use stmt.query(...) instead of stmt.send(...) the PIVOT works.  This is what tipped me off: https://duckdb.org/docs/api/wasm/query - "// ... and run the query with materialized results".  

```js
    async simpleQuery(query){
        const connection = await this._db.connect();
        let result
        try{
            result = await connection.query(query);
            return result.toArray();
        } finally {
            await connection.close()
        }
    }
```

I wonder if DuckDBClient could be enhanced to not always stream query results?

**Comment by mbostock** [comment]
Yes, looks like we should change the DuckDBClient to use `connection.query` instead of `statement.send` in the cases where we don’t actually need streaming (such as the `sql` tagged template literal).
