### ISSUE TITLE
Reactive “dark” variable

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#1018]
```js
const dark = Generators.observe((change) => {
  const media = matchMedia("(prefers-color-scheme: dark)");
  const changed = (event) => change(event.matches);
  media.addEventListener("change", changed);
  change(media.matches);
  return () => media.removeEventListener("change", changed);
});
```

**Comment by Fil** [comment]
This returns the user preference. It is what we want if the project has support for dark mode. However, I found it more convenient to return false _always_ when the page has only a light theme (and conversely, if the sole theme is dark, return true), independently of user preference.

The idea is that you could use this variable in a generic component without knowing in advance if it will be used on a page that supports dark mode.

On pangea I'm calling your function **darkPrefers** (user dark mode preference), and for **dark** I'm using this variant:

```js
// Watches dark mode based on theme and user preference.
// TODO: in preview, also watch for changes in the theme meta.
export const dark = Generators.observe((change) => {
  const media = matchMedia("(prefers-color-scheme: dark)");
  const changed = () => change(getComputedStyle(document.body).getPropertyValue("color-scheme") === "dark");
  changed();
  media.addEventListener("change", changed);
  return () => media.removeEventListener("change", changed);
});
```

I've started work on a (much too long and messy) [dark mode guide](https://observablehq.observablehq.cloud/pangea/support/dark-mode).

**Comment by mbostock** [comment]
I guess I’m not sure when I would use your version of `dark` — if I’m on a page that doesn’t support both light and dark mode, why would I care what the value of `dark` is? It’s always either true or false.

Your variant makes sense if I’m building a component that can work on any page, and I don’t know what the theme is. That makes sense as a library author. But it also feels more complex than necessary for most users, who will know whether they need to support both modes, and hence reach for a reactive `dark` variable.

**Comment by Fil** [comment]
It's all the same to the user, but safer. Here's my scenario: in 2024, you're developing a page that supports dark mode, you add the reactive **dark** thing to select a color scheme and a mix-blend-mode. Then a year later, for some reason you (or someone else) change the theme to "light-awesome" because this new light theme is awesome. But you forget (or they don't know) that _dark_ is not going to adjust, and you don't see it because your system settings is for light mode. A visitor comes, who has the dark preference system, and the page looks bad.

**Comment by Fil** [comment]
Also, we all copy and paste a lot — as library developers and as website developers and as chat-gpt-powered developers — so if an example use _dark_, it will be reused as is, whether the page supports dark mode or not.

**Comment by mbostock** [comment]
Sounds good. I’m convinced! Especially because `color-scheme` is how native controls handle light and dark mode. Seems natural that we would encourage a consistent approach for user content.
