### ISSUE TITLE
Using FileAttachment from js imports?

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1046]
In the `penguincount.js` file it's possible to

```js
import {FileAttachment} from "observablehq:stdlib";
const penguins = await FileAttachment("penguins.csv").csv();
export const count = penguins.length;
```

And in `penguinscount.md`:
```js
import {count} from "./penguincount.js";
display(count);
```

However, this does not seem to register the penguins.csv file: in other words, the page only works (displays _344_) if it also contains a reference to `FileAttachment("penguins.csv")`.

**Comment by mbostock** [comment]
You need to say

```js
import {FileAttachment} from "npm:@observablehq/stdlib";
```

Maybe we should disallow `observablehq:` imports. That’s only intended for internal use at the moment.
