### ISSUE TITLE
A + in a URL is sometimes decoded as a space

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1055]
This affects at least one user who reported that their site hosted on S3 was broken. `dist/_npm/d3@7.9.0/+esm.js` was 403, but `dist/_npm/d3@7.9.0/%2Besm.js` was 200.

We could (must) url-encode the `src`. But, it's going to look ugly… maybe we can find a better way. (Also we should make sure that we url-encode everything that needs to be encoded.)

**Comment by Fil** [comment]
I'll try that. It will also clarify the code (+esm will be the source, and -esm will be our copy).

**Comment by mbostock** [comment]
Oops, sorry I already started… 😬

**Comment by mbostock** [comment]
We should probably still URL-encode such links as needed… kind of a separate bug?

**Comment by Fil** [comment]
Yes we must urlencode the link _and_ it's nicer to use an underscore (#1056) because the urlencoded + is "ugly".

**Comment by Fil** [comment]
not planning to urlencode everything for now—it's too messy
