### ISSUE TITLE
Framework URLs not resolving with different slash combinations

### ISSUE THREAD

**Issue by zachbogart** [observablehq/framework#1067]
On the Framework site, visiting pages with/without leading slashes can lead to the pages note being resolved correctly, which I think may be due to routing behaviors.

For example, there is a [JavaScript folder](https://github.com/observablehq/framework/tree/main/docs/javascript), where the main index page named `javascript.md` is outside of the folder in the docs root. If I visit that page as:

```
https://observablehq.com/framework/javascript
```

it works, but if I visit with an added slash:

```
https://observablehq.com/framework/javascript/
```

I get the page, but with no formatting.

I am having similar troubles with my test build. I have a [demo folder
](https://github.com/cookwcode/restaurant/tree/main/docs/demo) where I put the index page within the folder. On build I get a similar result, but flipped from above. Visiting with a leading slash works:

```
https://cookwcode.observablehq.cloud/restaurant/demo/
```

But visiting without a leading slash fails:

```
https://cookwcode.observablehq.cloud/restaurant/demo
```

**Thinking**: Once site is built, I'm trying to understand how project structure will affect URL routing. 

Thanks.

**Comment by mbostock** [comment]
This `https://observablehq.com/framework/javascript/` should really be a 404. It’s not linked anywhere. If you make up a URL, you shouldn’t expect it to work, or in general adding a slash to a URL without (or with) a file extension isn’t guaranteed to produce a valid URL.

On the other hand, it is fairly common that a URL with a trailing slash is also accessible without a trailing slash. So in your second case, `https://cookwcode.observablehq.cloud/restaurant/demo` should redirect to `https://cookwcode.observablehq.cloud/restaurant/demo/`. This isn’t something that Framework can do, however — it’s a function of your static host service. So this is arguably a bug (or a missing feature) in the Observable platform/project hosting.

**Comment by mbostock** [comment]
For what it’s worth, we put a workaround for this in the custom 404 page:

https://github.com/observablehq/framework/blob/84d3e5c3a4809d0062dabc815c94402eaef9c838/src/render.ts#L43-L54

But I don’t think the Observable platform yet supports custom 404 pages.

**Comment by mbostock** [comment]
Update: Observable does support custom 404 pages, so you can fix this by creating a `404.md` (which can contain whatever you like).

**Comment by mbostock** [comment]
Closing as this is an issue with the hosting service rather than Framework itself.
