### ISSUE TITLE
Define sql connectors to live data

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1072]
```yaml
---
sql:
  mytable: ${a live expression}
---
```

**Comment by mbostock** [comment]
What is this? I don’t think we want this. It goes against static analysis. You can do this by manually declaring a `DuckDBClient` as shown in other issues but I’m pretty strongly opposed to putting reactive JavaScript expressions within front matter.

**Comment by Fil** [comment]
The idea is that sql fenced blocks are so great to use, I'm trying to find the shortest route to them from live data.
