### ISSUE TITLE
DuckDB statistical aggregate functions not available?

### ISSUE THREAD

**Issue by jaanli** [observablehq/framework#1092]
I am trying to add a `Plot.ruleX` marker (https://observablehq.com/plot/marks/rule#ruleX) to these plots, by first computing the median: 

````
```js
const medianIncome = await db.query(`
  SELECT
    quantile_cont(0.5) WITHIN GROUP (ORDER BY income) AS median_income
  FROM data
  WHERE year = ${selectedYear} AND puma = '${selectedPUMA}' AND state_code = '${selectedStateCode}';
`);
```
````

And then adding the rule mark into the `marks` array of the `Plot`:

```
      Plot.ruleX([medianIncome], {stroke: "red", strokeWidth: 2})
```

However, this yields the following error: `Error: Parser Error: Unknown ordered aggregate "quantile_cont".` despite this being a valid aggregate function in duckdb: https://duckdb.org/docs/sql/aggregates.html

Full code: https://github.com/jaanli/american-community-survey/blob/main/docs/new-york-area.md

Demo of what I'm trying to add the rule mark to, in order to make it easier to see patterns among 169 different census-defined microdata areas in the 2020 core-based statistical area of New York-Newark-Jersey City: https://jaanli.github.io/american-community-survey/new-york-area

Super cool to see how easy this is with Observable + Claude 3 Opus helping out lots to counteract my noob javascript skills :)

**Comment by mbostock** [comment]
Probably you’re trying to use features that haven’t been released yet. The default version of DuckDB-Wasm is 1.28.0. If you want to load the prerelease version of 1.28.1 you’ll have to import it explicitly and specify the version.

**Comment by mbostock** [comment]
I looked into this further. You’re calling [`quantile_cont`](https://duckdb.org/docs/sql/aggregates.html#statistical-aggregates) which is a statistical aggregate function, but you should be calling [`percentile_cont`](https://duckdb.org/docs/sql/aggregates.html#ordered-set-aggregate-functions) which is an ordered set aggregate function.

Here is an example of using `percentile_cont` with the `gaia-sample.parquet` sample data:

```sql
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY phot_g_mean_mag) AS median_phot_g_mean_mag,
FROM gaia
```

And here is an example of using `quantile_cont` on the same:

```sql
SELECT quantile_cont(phot_g_mean_mag, 0.5) AS median_phot_g_mean_mag,
FROM gaia
```

**Comment by jaanli** [comment]
Understood, thank you @mbostock ! 

I can't use `percentile_cont` directly, so am trying more duckdb magic: 

````
```js
const medianIncome = await db.query(`
  SELECT
    percentile_cont(0.5) WITHIN GROUP (ORDER BY income) AS median_income
  FROM data, generate_series(1, CAST(count AS INT))
  WHERE year = ${selectedYear} AND puma = '${selectedPUMA}' AND state_code = '${selectedStateCode}';
`);
```
````

This is needed because the raw rows are too large and the counts need to be unnested using `generate_series` appropriately - I followed the API example that has a similar schema and includes a `count` column: https://observablehq.com/framework/examples/api/

Will figure this out! 🙏  Thank you again!
