### ISSUE TITLE
Windows: Framework init copies files even when no sample files option select resulting in Windows 11 permissions error

### ISSUE THREAD

**Issue by JustinGOSSES** [observablehq/framework#1104]
Appreciate the work being done in the other issues to get this working on Windows. 

Unsure if this is a general Windows problem or specific to my corporate protections layered on top. I've not seen it before with previous software development, but it shares some language with other issues in web search results. 

This terminal export is on Windows 11 WSL run in administrator mode. 
```
npm init "@observablehq"
┌   observable create  v1.3.0
│
◇  Where to create your project?
│  ./framework
│
◇  What to title your project?
│  framework
│
◇  Include sample files to help you get started?
│  No, create an empty project
│
◇  Install dependencies?
│  No
│
◇  Initialize git repository?
│  No
│
◐  Copying template files.│
■  Error: EPERM: operation not permitted, copyfile '/home/UserName/.npm/_npx/f417d01c081ec748/node_modules/@observablehq/framework/templates/empty/docs/aapl.csv' -> 'framework/docs/aapl.csv'
│
●  To see the full stack trace, run with the --debug flag.
│
│  If you think this is a bug, please file an issue at
└  https://github.com/observablehq/framework/issues

■  Canceled
```

Different error message on powershell terminal and git bash and VS Code running locally terminal but maybe related error: 

```
PS C:\Users\username\OneDrive\Code\OpenSource\OSPO> npm init "@observablehq"
Γöî   observable create  v1.3.0
Γöé
Γûá  Error: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
Γöé
ΓùÅ  To see the full stack trace, run with the --debug flag.
Γöé
Γöé  If you think this is a bug, please file an issue at
Γöö  https://github.com/observablehq/framework/issues

npm ERR! code 1
npm ERR! path C:\Users\username\OneDrive\Code\OpenSource\OSPO
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c observablehq-create
```

Saying no to sample file and dependencies does not prevent error. 

I've tried to clean the npm cache as well as that was suggested for vaguely similar error message, but not luck.
```
npm cache clean --force
```
I'm running npm version v20.11.1

**Comment by mbostock** [comment]
Even the “empty” template still has _some_ files in it — it just has a smaller set of files than the default template with more example pages. (You can [browse the template sources](https://github.com/observablehq/framework/tree/main/templates) to see what they contain.) If the templates didn’t have any files, then `observable create` would just create an empty folder, which wouldn’t be much of a template. 😅

So, not really sure that we can do anything here. It looks to me like you’re trying to create the project on a part of your file system that you don’t have permission to write to. Perhaps you need to try running it in a different directory?
