### ISSUE TITLE
Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by iconara** [observablehq/framework#1119]
When I use the SQL feature, in some circumstances I get "TypeError: Cannot convert a BigInt value to a number" when trying to plot the results of a query.

It seems the Arrow table that is returned from queries can contain numeric types that Plot doesn't support. All I do is queries like this:

```
'''sql id=myTimeseries
SELECT date,
       SUM(my_integer_column) AS my_integer_column
  FROM my_table
 GROUP BY 1
 ORDER BY 1
'''
```

and pass that into Plot.

I also get the same error when I try to pass a value into a D3 formatter, for example:

```
'''js
const integerFormat = d3.format(',d')
'''

${integerFormat(myTimeseries.get(0).my_integer_column)}
```

**Comment by Fil** [comment]
Can you give more specifics of how you pass it to Plot? We've fixed a number of cases where it wouldn't work, but we might have missed some (https://github.com/observablehq/plot/issues/1278).

A way to fix this is to cast the values to "normal" numbers in DuckDB:

```
SELECT date,
       SUM(my_integer_column)::INT AS my_integer_column
```

Doing it in JavaScript is also possible but requires more work:

`${integerFormat(Number(myTimeseries.get(0).my_integer_column))}`

**Comment by iconara** [comment]
I tried narrowing down the problem to something reproducible:

```
'''sql id=rows
WITH data (n) AS (VALUES (1234567890), (9876543210))
SELECT SUM(n) AS n
FROM data
'''

Expected: ${1234567890 + 9876543210}<br>
Raw: ${rows.get(0).n}<br>
Number(): ${Number(rows.get(0).n)}<br>
parseInt(): ${parseInt(rows.get(0).n)}<br>
d3.format: ${d3.format(',d')(rows.get(0).n)}
typeof: ${typeof rows.get(0).n}<br>

${Inputs.table(rows)}
```

This will output:

```
Expected: 11111111100
Raw: 2521176508200
Number(): 1.2438821514721054e+31
parseInt(): 11111111100
d3.format:
TypeError: Cannot convert a BigInt value to a number
d3.sum: ${d3.sum(rows, (d) => d.n)}
TypeError: Cannot convert a BigInt value to a number
typeof: object
```

I also tried reducing the issue with Plot, and as far as I can tell the error comes from my code using `Plot.groupX({y: 'sum'}, …)`, which I assume uses something like `d3.sum` under the hood.

As you can see there seems to be multiple issues. `Number(…)` does not correctly coerce the `BigInt` into a number. The expected number is large, but not larger than `Number.MAX_SAFE_INTEGER`. `parseInt(…)` has no problem coercing it into the correct number.

I can't fix the issue by casting to `INT` in my SQL, since the values are larger than 2^31.

**Comment by iconara** [comment]
It gets even weirder:

```
'''sql id=rows
WITH data (n) AS (VALUES (1234567890), (9876543210))
SELECT SUM(n) AS n
FROM data
UNION ALL
SELECT 1234567890 + 9876543210 AS n
'''

Number(): ${Number(rows.get(0).n)}<br>
Number(): ${Number(rows.get(1).n)}<br>
parseInt(): ${parseInt(rows.get(0).n)}<br>
parseInt(): ${parseInt(rows.get(1).n)}<br>
```

Outputs:

```
Number(): 1.2438821514721054e+31
Number(): 4.460189873590169e+44
parseInt(): 11111111100
parseInt(): 11111111100
```

**Comment by mbostock** [comment]
You can cast to ::float in SQL.

**Comment by mbostock** [comment]
This appears to be covered by https://github.com/apache/arrow/issues/37920.
