### ISSUE TITLE
getting-started needs await for FileAttachment

### ISSUE THREAD

**Issue by g1776** [observablehq/framework#1138]
In the `getting-started` tutorial, loading the weather data:

```js
const forecast = FileAttachment("./data/forecast.json").json();
display(forecast)
```

results in displaying an empty Promise:

![image](https://github.com/observablehq/framework/assets/22138506/c74b5554-a582-48e5-a52a-8338751a8d3c)

An await needs to be added:

```js
const forecast = await FileAttachment("./data/forecast.json").json();
display(forecast)
```

![image](https://github.com/observablehq/framework/assets/22138506/6e839ed6-b201-4438-8114-d6003e6ef0e9)

**Comment by Fil** [comment]
The tutorial mentions _ another code block_, in which case you don't need await, because values are implicitly awaited between code blocks. But I agree we should make this stand out more clearly in the documentation.
