### ISSUE TITLE
Router error while serve static files

### ISSUE THREAD

**Issue by m1911star** [observablehq/framework#1150]
To reproduce with official repo:
1. Run yarn docs:build;
2. npx http-server ./docs/.observablehq/dist/
3. then navigate to /javascript

https://github.com/observablehq/framework/assets/4948120/4053c325-8853-4a5f-9a0f-225e186162e1

It turns out that there are base router for `/javascript` and sub router `/javascript/*`
static output files stucture as below:

<img width="380" alt="image" src="https://github.com/observablehq/framework/assets/4948120/af968d55-51ab-41ba-a439-ade2a02bdc8b">

<img width="468" alt="image" src="https://github.com/observablehq/framework/assets/4948120/af1ac004-aec9-4ac9-abd0-c279dc67f4a9">

So when navigate to /javascript，page not found

What I propose here, we can try:
1. just map javascript.md to javascript/index.html
2. change the type definition of Section/Page in observablehq.config.ts, add path to Section to define the section router file

<img width="833" alt="image" src="https://github.com/observablehq/framework/assets/4948120/b2cbe0e8-9922-4143-9adb-6cd162ddbd66">

**Comment by mbostock** [comment]
You need to set the [**cleanUrls** config option](https://observablehq.com/framework/config#cleanurls) to false if you’re using a server that doesn’t support clean URLs (such as `http-server`).
