### ISSUE TITLE
Support loading JS objects as DuckDBClient databases via JSON

### ISSUE THREAD

**Issue by bburky** [observablehq/framework#1173]
It would be nice to provide better support for loading a JS object into DuckDB as JSON. The SQL query syntax can be quite nice to query nested JSON structures easily (`unnest()` works great) and display results a table.

I read through the code and realized this isn't too hard to implement and found a hacky way to do it:
https://github.com/observablehq/framework/blob/e6e4774739837a60f7a93e24fc57ca69effe580e/src/client/stdlib/duckdb.js#L217

```js
const my_object = [{foo: 1, bar: [{baz: 2}, {baz: 3}]}, {foo: 4, bar: [{baz: 5}, {baz: 6}]}];

const blob = new Blob([JSON.stringify(my_object)], {
  type: "application/json",
});
const sql = DuckDBClient.sql({
  my_object: {
    file: {
      url: () => URL.createObjectURL(blob),
      arrayBuffer: () => blob.arrayBuffer(),
      mimeType: blob.type,
    },
  },
})'
```

```sql
select foo, unnest(bar).baz from my_object;
```

Maybe provide a wrapper function that converts a JS object (or a JSON string?) into an in-memory fake-FileAttachment object for use with some of the Framework libraries? You could extend this to support other MIME types if you want too. Alternately, you could just add support for Blob objects to the API where FileAttachment is currently supported.

**Comment by bburky** [comment]
Nevermind, I guess this is actually what it already doing if you pass an arrray object to DuckDB (`insertArray()` internally) and it uses `arrow.tableFromJSON(array)` to pass the data to DuckDB. However with some complex nested JSON (this [API response](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases)) I get the error `RuntimeError: Unable to infer Vector type from input values, explicit type declaration expected.`

If I serialize my JSON with plain `JSON.stringify()` and load it as a blob as I do above, I get no errors.

I suppose the issue I filed is actually already implemented, but I get errors trying to use it.

**Comment by mbostock** [comment]
Can you share a reproduction of what’s not working for you? I just tested this, and it worked as expected:

````md
```js echo
const my_object = [{foo: 1, bar: [{baz: 2}, {baz: 3}]}, {foo: 4, bar: [{baz: 5}, {baz: 6}]}];
const sql = DuckDBClient.sql({my_object});
```

```sql echo
SELECT * FROM my_object;
```
````

**Comment by mbostock** [comment]
Ah, you linked the example data that can reproduce. Here is a minimal reproduction:

````md
```sql echo
SELECT * FROM my_object;
```

```js echo
const my_object = [{assets: [{url: "1"}]}];
const sql = DuckDBClient.sql({my_object});
```
````

**Comment by mbostock** [comment]
Unfortunately, this is a bug in Apache Arrow. We should file a bug over there. Here is a reproduction:

````md
```js echo
const array = [{assets: [{url: "1"}]}];
const table = Arrow.tableFromJSON(array);
```
````

**Comment by mbostock** [comment]
Already filed here: https://github.com/apache/arrow/issues/33394

I’ll upvote the issue. Hopefully they will fix it soon!

**Comment by bburky** [comment]
Thanks for investigating and identifying a minimal reproduction. I'll continue to use a workaround for now and I'll track the upstream issue until it's resolved.
