### ISSUE TITLE
Regression: the sql page is broken

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1185]
https://observablehq.com/framework/sql is broken and has this error in the console:

> error in duckdb worker: Uncaught SyntaxError: Unexpected token 'export'

Bisected to first bad commit = ac66ff4d2d7d0df768c638e429513adcc4a15654

**Comment by Fil** [comment]
The test for isJavaScript introduces the bug:

```
  a: '/_npm/@duckdb/duckdb-wasm@1.28.0/dist/duckdb-browser-mvp.worker.js',
  b: '/_npm/@duckdb/duckdb-wasm@1.28.0/dist/duckdb-browser-mvp.worker.js._esm.js
```
before, we were returning `a` (it worked); now returning returning `b` (breaks).

**Comment by mbostock** [comment]
Oof. Yes, we’ll need to rethink this.

**Comment by mbostock** [comment]
We’ll need to think about how we would import a “raw” .js from `_node` too, then. I was almost wondering if we should have a `/+raw` instead of `/+esm` and effectively invert the default.
