### ISSUE TITLE
Generators.width becomes 0 on hot reload (dom element replacement)

### ISSUE THREAD

**Issue by declann** [observablehq/framework#1194]
Hi,

As mentioned in #1193 I'm nesting some html/markdown/js. This is to make a 2 column layout and so I also use a `Generators.width` to detect width of one of my containers.

This basically works, but the value becomes 0 and stops tracking element size on hot reload affecting any of the container content (due to real dom element replacement).

If it's desirable I guess `Generators.width` could observe dom mutations, but it also needs to update the real DOM element its tracking - would that work? I'll report here if I get to try this.

Updated demo: https://raw.githubusercontent.com/declann/framework-reactive-html/main/docs/index.md

Cheers
Declan

**Comment by mbostock** [comment]
It’s zero because the element is no longer attached to the DOM (because it got replaced). If you can share more about what you’re trying to do, perhaps we can suggest an alternative pattern, but the behavior of Generators.width is intended here.
