### ISSUE TITLE
Vega-Lite rendering fails when block ends with a semicolon

### ISSUE THREAD

**Issue by danmarshall** [observablehq/framework#1201]
I found this 🐞 when using autoformat with VSCode, which ends js blocks with a semicolon.

### Vega-Lite

```js echo
vl.render({
  spec: {
    $schema: "https://vega.github.io/schema/vega-lite/v5.json",
    description: "A simple bar chart with embedded data.",
    data: {
      values: [
        { a: "A", b: 28 },
        { a: "B", b: 55 },
        { a: "C", b: 43 },
        { a: "D", b: 91 },
        { a: "E", b: 81 },
        { a: "F", b: 53 },
        { a: "G", b: 19 },
        { a: "H", b: 87 },
        { a: "I", b: 52 },
      ],
    },
    mark: "bar",
    encoding: {
      x: { field: "a", type: "nominal", axis: { labelAngle: 0 } },
      y: { field: "b", type: "quantitative" },
    },
  },
})  //; //uncomment the semicolon to see a bug
```
Expected: 
![image](https://github.com/observablehq/framework/assets/11507384/0896ce19-59e7-42ae-92e3-455b4d3692e9)

Actual:
![image](https://github.com/observablehq/framework/assets/11507384/fe229f97-ad47-430a-aadd-5181170ead88)

This seems to be the only component I found that has this behavior, others handle an ending semicolon as expected.

**Comment by mbostock** [comment]
Yep, this is the intended behavior. You can find an explanation here:

https://observablehq.com/framework/javascript/display#implicit-display

You can either remove the semicolon or add an explicit `display` depend on your preference.

**Comment by danmarshall** [comment]
Ok thanks for the fast reply! For those dependent on auto-formatting here is what I used:

```js echo
display(await vl.render({ spec }));
```
