### ISSUE TITLE
omit 3 sample files when "empty project" is selected

### ISSUE THREAD

**Issue by borango** [observablehq/framework#1235]
really a minor issue here:

## Expected behaviour

When I run ```observable create``` and I select...
<pre>
◇  Include sample files to help you get started?
│  No, create an empty project
</pre>
... then I expect an empty ```docs``` folder.

## Observed behaviour

Less than in the "full" version, but still I get 3 sample files:
1. aapl.csv
2. index.md
3. penguins.csv

- - -
No urgency because I can easily work around by removing these 3 files manually. 

Which I routinely do, so for me personally it would be an enhancement to have completely empty docs.

**Comment by Fil** [comment]
This was addressed in #1219 ; the “empty” template is not really empty, but only a (very bare bones) index.md file.
