### ISSUE TITLE
Docs unclear on when data loaders are run during build

### ISSUE THREAD

**Issue by burakbudanur** [observablehq/framework#1242]
Presently the docs read

"[Caching] Observable Framework considers the cache “fresh” if the modification time of the cached output is newer than the modification time of the corresponding data loader. 
... 
[Building]
...
The data loader cache is respected during build. This allows you to bypass some or all data loaders during build, if the previously built data is still fresh." 

which I interpret as "If the data loader's modification time is more recent than that of the cached data, then the data loaders are run during the build." This, however, is not the case. See also: https://github.com/observablehq/framework/issues/140

**Comment by mbostock** [comment]
Yes, we should clarify this. During build, the only thing that matters is the whether the output is _present_ in the cache, not how old it is. (This is because CI caches such as GitHub Actions typically don’t preserve modification times.)

Similar confusion in #1148.
