### ISSUE TITLE
Sidenav items do not (always) show active when they should, using cleanUrls: false

### ISSUE THREAD

**Issue by rossmills99** [observablehq/framework#1248]
There seem to be two issues but I assume they are related.

## 1. Sidenav items do not show correct active state when running from the dev server, when `cleanUrls: false` configuration is used

To reproduce, set `cleanUrls: false` in configuration, then run the dev server.  Notice the sidenav items never show the correct active state.

I tried to fix this myself, in render.ts:

```diff
-function renderListItem(page: Page, path: string, normalizeLink: (href: string) => string): Html {
+function renderListItem(page: Page, path: string, normalizeLink: (href: string) => string, cleanUrls: boolean = true): Html {
   return html`\n    <li class="observablehq-link${
-    normalizePath(page.path) === path ? " observablehq-link-active" : ""
+    normalizePath(page.path) + (cleanUrls ? "" : ".html") === path ? " observablehq-link-active" : ""
   }"><a href="${normalizeLink(relativePath(path, page.path))}">${page.name}</a></li>`;
 }
```

It seemed to work running from the dev server, but unfortunately when I build the project (`yarn docs:build`) and serve the resulting dist files, it doesn't work.

## 2. _Some_ sidenav items do not show correct active state when running the built files, when `cleanUrls: false`  configuration is used

When I removed my local changes and ran `docs:build`, with no changes other than the config entry `cleanUrls: false`, I found that the correct active state does seem to be applied for _most_ nav items - but not all of them!  For example, /javascript.html seems rendered properly:

![image](https://github.com/observablehq/framework/assets/5502815/8b3a15ae-a6bc-429f-beb0-64762ef6de91)

Whereas /reactivity.html is not:

![image](https://github.com/observablehq/framework/assets/5502815/147cefa5-c5ac-4e68-84a5-6eb450dbbf7a)

**Comment by Fil** [comment]
I can't reproduce this issue: when I build the documentation with cleanUrls: false I have the correct highlights.
![Capture d’écran 2024-04-16 à 16 35 30](https://github.com/observablehq/framework/assets/7001/e0600a85-4b37-4f1c-9800-afd65cd78b86)

Is it an OS or browser issue? Can you try and publish the broken site somewhere so we can see how it's rendering?

**Comment by mbostock** [comment]
The fact that it’s not applied consistently suggests that in build it is a browser caching issue, not a Framework bug. But we should fix preview for sure.
