### ISSUE TITLE
Data loader examples

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#1304]
- [x] Snowflake
- [x] PostgreSQL
- [x] Databricks
- [ ] #1343
- [ ] #1344
- [ ] #1345
- [ ] #1346
- [ ] #1347
- [ ] #1348
- [x] GitHub API
- [x] Google Analytics API (adapt [existing example](https://github.com/observablehq/framework/tree/main/examples/google-analytics))
- [ ] #1349
- [ ] [U.S. Census Bureau cartographic boundaries data loader example](https://mbostock.observablehq.cloud/framework-help/2024-05-01-census-boundaries/)

**Comment by mbostock** [comment]
Broke out into separate issues.

**Comment by benminer** [comment]
Hey @mbostock - any update on a BigQuery data loader example? I am having some issues...

I got a static data loader working with BigQuery:
```
// data/bigquery.ts
import { BigQuery } from "@google-cloud/bigquery";

const bigquery = new BigQuery();

export const runQuery = async (query) => {
  const [rows] = await bigquery.query(query);
  return rows;
};
```

This works fine loading _static_ data, like `countries`, from the database:

```
// data/countries.json.ts
import { runQuery } from "../bigquery";

process.stdout.write(
  JSON.stringify(
    await runQuery(`
SELECT country FROM $my-bg-table
`))
);
```

However, in the page I am trying to create, it needs to allow a viewer to pick a country from a dropdown. The dropdown works just fine when running, but I can't figure out how to do a dynamic query using my new `bigquery.ts` file. When I import in a "```js" tag, I get `TypeError: Failed to resolve module specifier 'data/bigquery'`. Running this with a `ts` tag simply displays the code, but doesn't run anything. Installing`@google-cloud/bigquery` via `npm i` also throws: `TypeError: Failed to resolve module specifier '@google-cloud/bigquery'` - which doesn't make sense, since it's installed. Using the `npm:` prefix throws CJS bundle errors from esbuild.

```
// my dashboard.md
```js
const countries = await FileAttachment("data/countries.json").json();
\```

```js
const countrySelect = Inputs.select(
  countries.map((obj) => obj.country),
  {
    label: "Select Country",
    value: "ES",
  }
);
display(countrySelect); // this works!
\```

```js
import { runQuery } from "data/bigquery"; // this throws
\```
```

I've tried importing the `BigQuery` library directly in a `js` block, but that leads to bundle errors from Rollup:
` Failed to bundle using Rollup v2.79.1: the file imports a not supported node.js built-in module "fs".`

```
```js
import { BigQuery } from "npm:@google-cloud/bigquery"; // throws
import { BigQuery } from "@google-cloud/bigquery"; // throws
const { BigQuery } = await import('@google-cloud/bigquery') // throws
const bigquery = new BigQuery();
const data = await bigquery.query(`
SELECT country, ymd, hour
FROM \`my-bg-table\`
WHERE ymd >= "2024-06-20"
and country= ${countrySelect}
and hour is not null
  and region is null
order by ymd, hour
`);
display(data);
\```
```

This makes sense, but I have a feeling I am doing something wrong here. I am new to @observable overall, so there may be something obvious here. Any help is very appreciated.

**Comment by Fil** [comment]
@benminer please open a [discussion](https://github.com/observablehq/framework/discussions) in the forum.
