### ISSUE TITLE
Add Nushell support for data loader

### ISSUE THREAD

**Issue by linux-china** [observablehq/framework#1309]
Nushell has good support for CSV, YAML:  https://www.nushell.sh/book/loading_data.html  
Is it possible to add `.nu - Nushell script (nu)` support?

```
.js - JavaScript (node)
.ts - TypeScript (tsx)
.py - Python (python3)
.R - R (Rscript)
.rs - Rust (rust-script)
.go - Go (go run)
.java — Java (java; requires Java 11+ and [single-file programs](https://openjdk.org/jeps/330))
.jl - Julia (julia)
.php - PHP (php)
.sh - shell script (sh)
.exe - arbitrary executable
```

**Comment by mbostock** [comment]
You can add any interpreter you like using the [**interpreters** config option](https://observablehq.com/framework/config#interpreters).
