### ISSUE TITLE
When creating a new project, we get a warning about the unspecified root

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1329]
> `npm init @observablehq`

……… (standard install)

> `npm run build`

Warning: the config file is missing the root option, which specifies the path to
the source root. The recommended source root is "src"; however, since docs
exists and was previously the default for this option, we will use "docs". You
can suppress this warning by specifying root: "docs" in the config file.

**Comment by mbostock** [comment]
I tested this so probably something else going wrong here. The templates do now specify the **root** option:

https://github.com/observablehq/framework/blob/2a9c4b5bee8fa303f6cfa5a50faf260943fb4100/templates/default/observablehq.config.js.tmpl#L23

**Comment by Fil** [comment]
yes it went await when I did `rm -rf ~/.npm/_npx`
sorry for the noise!
