### ISSUE TITLE
crash due to a regression in nwsapi (“Unexpected error: 'h1:not(:first-of-type),…' is not a valid selector”)

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1330]
see https://github.com/dperini/nwsapi/issues/114

this breaks the build of any project that has nwsapi@2.2.10 (2.2.9 is OK).

**Comment by Fil** [comment]
Add the following to the package.json:
```
  "overrides": { "nwsapi": "<2.2.10" },
  "resolutions": { "nwsapi": "<2.2.10" }
```

this will cover both yarn and npm.
Then run yarn install / npm install again.

**Comment by mootari** [comment]
Note that 2.2.8 also has a regression ([it fails](https://github.com/jsdom/jsdom/issues/3706) for "h1,h2"), so 2.2.9 appears to be the only safe version for now.
