### ISSUE TITLE
cdn.jsdelivr.net can time out on some modules, triggering an uncaught error

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1352]
With a page that contains:

~~~~md
```js echo
const Cite = import("npm:citation-js");
```
~~~~

loading the modules ends up in a breaking timeout (showing "fetch failed" on the page) on https://cdn.jsdelivr.net/npm/@citation-js/plugin-wikidata@0.7.11/+esm (which also fails if you try to open it independently of framework). In the log we see:

```
npm:@citation-js/plugin-wikidata@0.7.11/+esm → src/.observablehq/cache/_npm/@citation-js/plugin-wikidata@0.7.11/_esm.js
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    …
```

I initially thought this was a fluke, but trying to install the same module locally (`yarn add citation-js`) I see this warning:

`warning citation-js > @citation-js/plugin-wikidata > wikidata-sdk@8.1.1: wikidata-sdk has been renamed wikibase-sdk`

which might be the root cause.

Should our `npm:` resolver do some work to detect a rename? Should we catch this error? Should we just leave this as is? — it seems possible to load citation-js with: `import("npm:@citation-js/core");`

**Comment by mbostock** [comment]
Don’t think there’s anything we can do here.
