### ISSUE TITLE
H2 after H1 not showing correctly

### ISSUE THREAD

**Issue by rfsan** [observablehq/framework#1397]
If I create a page `new-page.md` and add the following content

```markdown
# Main title

## Subtitle 1

## Subtitle 2

```

The first H2 is rendered incorrectly

![image](https://github.com/observablehq/framework/assets/92990559/2d591296-c1b7-4f37-8e6f-b4f601610a30)

When I add some text between the H1 and the first H2 it works as expected

![image](https://github.com/observablehq/framework/assets/92990559/e5784bb2-12e6-4b11-a0ba-b3fb6a521aea)

I'm using Observable Framework version `1.8.0`

**Comment by mbostock** [comment]
This is by design. The h2 immediately following an h1 is interpreted as a subtitle. You can place any content in between to prevent this behavior, including an empty div.
