### ISSUE TITLE
Ignore loader cache modification time during build

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#140]
We ran into an issue using GitHub Actions where the cache action preserves modification times, but the checkout action does not, and so the loader sources always look newer than the cache, and hence the loaders run even though the cache is populated. So perhaps a better default during build is to ignore modification times, and simply check whether the files are present. This way it will work by default in GitHub Actions without workarounds such as

```
find docs/.observablehq/cache -type f -exec touch {} +
```

And you can always remove the cache before building if you want to force a clean build.

**Comment by burakbudanur** [comment]
I believe I am running into an issue that is related to this one. I would like to build my dashboard periodically using `npm run build` and aggregate new data after fetching entries later than the cash from a database. Per documentation, I thought if I update the modification times of the data loaders using 

`find docs/data/*py -type f -exec touch {} +`

before the build, this would enforce running the data loaders (in my case *.py files). This, however, is not the case.

**Comment by Fil** [comment]
@burakbudanur did you run `find docs/data/*py -type f ` separately to see if that gives you the expected list of files? (If you're using a glob pattern you could do `touch docs/data/*py` instead, it should be equivalent to what you describe above.)

**Comment by burakbudanur** [comment]
Yes. Also confirmed that the command indeed updates the last modification time.

**Comment by mbostock** [comment]
During build cache file modification times are ignored. So, delete the cache files you want to recompute instead of touching the data loaders. Touching is only something you do during preview.

(Also, file a separate issue or discussion if you want help rather that using a closed issue.)
