### ISSUE TITLE
Add option to disable spinner during deploys

### ISSUE THREAD

**Issue by mootari** [observablehq/framework#1446]
When an application logs the output of the `deploy` command, the spinner output "Server processing deploy" will appear in logs as displayed in the examples below. Without a progress bar (see #687) there is arguably not much value to it, and even with a progress status it may not be desirable to log the output in such detail.

A solution could be to add a `--no-progress` option to the `deploy` command (or globally) that would suppress any spinner output except for the `.stop()` message.

#### Output examples

Docker container logs:
~~~
◒  Server processing deploy
◐  Server processing deploy
<SNIP>
◑  Server processing deploy.
◒  Server processing deploy.
<SNIP>
◒  Server processing deploy..
◐  Server processing deploy...
◓  Server processing deploy...
◑  Server processing deploy...
◇  Deploy complete\n
~~~
GitHub action logs:
~~~
◒  Server processing deploy◐  Server processing deploy◓  Server processing deploy◑  Server processing deploy◒  Server processing deploy◐  Server processing deploy◓  Server processing deploy◑  Server processing deploy◒  Server processing deploy.◐  Server processing deploy.◓  <SNIP> Server processing deploy..◐  Server processing deploy..◇  Deploy complete
~~~

**Comment by mbostock** [comment]
I don’t think we should add a command-line flag for this. We should just fix #1447 by checking for a TTY before showing the spinner.
