### ISSUE TITLE
"Analyzing web logs" example page is erroring

### ISSUE THREAD

**Issue by franloza** [observablehq/framework#1463]
Hi! 👋 

It seems the [Analyzing web logs](https://observablehq.observablehq.cloud/framework-example-api/) example page is failing:

<img width="1281" alt="image" src="https://github.com/observablehq/framework/assets/9200682/5718dd30-98d4-44fb-8902-6668a3920cc5">

All the charts return the same error:

```
RuntimeError: import.meta.resolve is not a function. (In 'import.meta.resolve("../_npm/parquet-wasm@0.6.1/esm/parquet_wasm_bg.wasm")', 'import.meta.resolve' is undefined)
```

I built the example locally with the current `main` branch (41f874c93bab2bce9db9b373a7144d2bf7ca5835) and it's working, so it could be just a matter of rebuilding the page.

<img width="1352" alt="image" src="https://github.com/observablehq/framework/assets/9200682/e8a7d91a-9ae2-4473-b296-a89df47fa0ee">

**Comment by franloza** [comment]
Hi again!

I re-opened the website in private browsing (I use Safari Version 16.3 (18614.4.6.1.6)) and it's working, so the problem was on my end. 

I'm closing the issue.

**Comment by mbostock** [comment]
Here’s the compatibility table for [`import.meta.resolve`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve):

<img width="783" alt="Screenshot 2024-06-14 at 5 46 15 AM" src="https://github.com/observablehq/framework/assets/230541/c2f6072a-f738-4d12-b042-81a68a275ca7">

**Comment by franloza** [comment]
Hey @mbostock, thank you for the answer.

I forgot to point out that it worked on private browsing using Chrome  125.0.6422.142 (both locally and live versions). Anyway, the problem was on my end as I used an incompatible version of Safari (16.3), so there's nothing to fix here.

Thanks again!
