### ISSUE TITLE
The SVG from Observable is not well read by Microsoft Word.

### ISSUE THREAD

**Issue by Alex-rv150** [observablehq/framework#1494]
I'm using the function from https://observablehq.com/@d3/color-legend (Legend), but Word doesn't understand what the color of the text of the legend is

## I replaced some code and managed to solve the error.

function Legend(color, {
  title,
  tickSize = 6,
  width = 320, 
  height = 44 + tickSize,
  marginTop = 18,
  marginRight = 0,
  marginBottom = 16 + tickSize,
  marginLeft = 0,
  ticks = width / 64,
  tickFormat,
  tickValues,
axisColor = "black"                                                           **//  line added - Default axis color**
}

## Also edit the last block of code.

  svg.append("g")
      .attr("transform", translate(0,${height - marginBottom}))
      .call(d3.axisBottom(x)
        .ticks(ticks, typeof tickFormat === "string" ? tickFormat : undefined)
        .tickFormat(typeof tickFormat === "function" ? tickFormat : undefined)
        .tickSize(tickSize)
        .tickValues(tickValues))
      .call(tickAdjust)
      .call(g => g.select(".domain").remove())
      .call(g => g.append("text")
        .attr("x", marginLeft)
        .attr("y", marginTop + marginBottom - height - 6)
        .attr("fill", axisColor)                                                               **//line edited**
        .attr("text-anchor", "start")
        .attr("font-weight", "bold")
        .attr("class", "title")
        .text(title))
  .call(g => g.selectAll(".tick line").style("stroke", axisColor))        **// line added**
  .call(g => g.selectAll(".tick text").style("fill", axisColor));             **// line added**

**Comment by Fil** [comment]
thanks for sharing
