### ISSUE TITLE
Add support for Graph Objects to GraphViz DOT?

### ISSUE THREAD

**Issue by sbarre** [observablehq/framework#1531]
The [Framework documentation](https://observablehq.com/framework/lib/dot) says GraphViz DOT support comes from Viz.js.

The Viz.js documentation says it supports passing in a POJO [graph object](https://viz-js.com/api/#viz.Graph) as well as DOT syntax.

It would be very convenient if we could choose between the template literal or this alternate object format.

**Comment by mbostock** [comment]
For this, I would recommend using Viz.js directly instead of using our `dot` template literal. You can see how we load Viz.js here:

https://github.com/observablehq/framework/blob/main/src/client/stdlib/dot.js

So, to start:

```js
import {instance} from "npm:@viz-js/viz";

const viz = await instance();
```
