### ISSUE TITLE
Dashboards as consumers of notebook artifacts

### ISSUE THREAD

**Issue by cinxmo** [observablehq/framework#154]
**Description:**
Easy export and/or store the contents of a notebook into an Observable artifacts repository.

**Why:**
Notebooks are valuable because they are quick ways to explore data. The user can quickly iterate and filter data through a DTC, create a helper function to create an SVG, and share contents of notebooks with a team member who also has Observable.
Notebooks are good for content _creation_ but not necessarily content _presentation_. Notebooks can provide the building blocks for dashboards and already have permissions baked into a particular view. Artifacts derived from a notebook should have the same permissions as the notebook themselves unless granted otherwise.

**Details:**
Have a button or some UI in for a single cell that publishes to the Observable artifacts repository. Expose extra scopes as part of the `observable login` command and a new set of APIs to fetch/download the artifacts. Users of the CLI can call these Observable endpoints within a data loader given that they've authenticated via `observable login`. 

**Why Part 2:**
Notebooks are constantly changing but artifacts are version-controlled. The act of promoting parts of a notebook to an artifact means the user/team is "locking in" the changes and having it be ready for production. We can also think about the possibilities of having a scheduled run with new artifacts posted on a dedicated time interval.

**Inspiration:**
- [JFrog Artifactory](https://jfrog.com/blog/what-is-artifactory-jfrog/)
- [JFrog REST APIs](https://jfrog.com/help/r/jfrog-rest-apis/introduction-to-the-artifactory-rest-apis)

**Comment by Fil** [comment]
closing as not planned; but it's a good idea to simplifying making artifacts from a project (e.g. with playwright).
