### ISSUE TITLE
cache breaking hashes: behavior for dev server

### ISSUE THREAD

**Issue by declann** [observablehq/framework#1550]
Hi,

Cache breaking hashes interfere with debugging experience in web browsers e.g. breakpoints in javascript imports can't be maintained across edits.

When using the dev server, perhaps it would be useful to turn it off, or to provide this option?

**Comment by mbostock** [comment]
Without changing the URL, we wouldn’t have a way to implement hot module replacement. (An import with the same URL cannot be redefined.) So I don’t think this is fixable, sorry!

**Comment by declann** [comment]
Ah, that's interesting. Thanks for the explanation!
