### ISSUE TITLE
Heading slugs could be friendlier

### ISSUE THREAD

**Issue by dleeftink** [observablehq/framework#1552]
When linking to headings on a Framework page, slugs are generated in a manner inconsistent with other static site generators/GitHub. 
For instance, when linking to a heading in a source file on GitHub will make the link incongruent with the page URL slug under the current sanitisation scheme:

```
https://github.com/suptext/suptext.github.io/blob/main/code/from/2024/07/26/building-quickset.md#whats-your-path
```

```
https://suptext.is/from/2024/07/26/building-quickset#what%E2%80%99s-your-path%3F
```

Instead of:

```
https://suptext.is/from/2024/07/26/building-quickset#whats-your-path
```

I think the way GitHub sanitises heading slugs is the way to go.

**Comment by mbostock** [comment]
There’s no guarantee we’ll match whatever GitHub does, but we can explore making friendlier slugs. We use markdown-it-anchor.

https://www.npmjs.com/package/markdown-it-anchor#user-friendly-urls
