### ISSUE TITLE
Is there a way to remove old files?

### ISSUE THREAD

**Issue by simon-mo** [observablehq/framework#1556]
On the platform, it seems some old files are cached until some unknown TTLs? We have been reducing our file sizes significantly, now at
```
┌ (4 pages)          Page      Imports        Files
├── github          10 kB       607 kB        99 kB
├── index            3 kB        49 kB        24 kB
├── perf            31 kB       728 kB       229 kB
└── usage           12 kB       949 kB     7.834 MB
```

and still getting this on deploy
```
●  Deploying to vLLM Dashboard v0 (@simon-mo-workspace/vllm-dashboard-v0).
25l│
◒  Sending file manifest to server◐  Sending file manifest to server◓  Sending file manifest to server◑  Sending file manifest to server◒  Sending file manifest to server◐  Sending file manifest to server◓  Sending file manifest to server◑  Sending file manifest to server◒  Sending file manifest to server.◐  Sending file manifest to server.◓  Sending file manifest to server.◑  Sending file manifest to server.◒  Sending file manifest to server.│
■  Error: Server rejected deploy manifest: deploy size of 49.9 MB exceeds remaining
│  quota of 43.9 MB
│
│  If you think this is a bug, please file an issue at
└  https://github.com/observablehq/framework/issues
■  Canceled
```

**Comment by mythmon** [comment]
Previous deploys still count towards your file quota for 28 days (we're working on a way to delete them to clear that up, though). If you contact support@observablehq.com, our support team can help you with your quota issues though.

**Comment by mbostock** [comment]
Based on your description, I am guessing that you are using DuckDB (perhaps indirectly SQL cells); unfortunately DuckDB-Wasm’s WebAssembly files are not currently tracked by the table you quote since they are loaded dynamically, and so even though the page size estimates are small, you’ll need to check the generated `dist` directory to see what the actual built file sizes are in total.

As to why DuckDB’s WebAssembly files are not tracked in this table:

> The “imports” column only tracks the size of static imports, not dynamic imports or import resolutions (import.meta.resolve). This means DuckDB’s (large) WebAssembly files aren’t counted. Framework knows that these files are referenced, but can’t know for sure whether they will actually be loaded (or when) because it’s not statically analyzable. So they’re not currently included in the tally. Maybe we could list them in a separate column in the future.

**Comment by simon-mo** [comment]
Thank you for the quick response! Let me check...

**Comment by simon-mo** [comment]
Oh you are exactly right 
```
 39M	dist/_npm/@duckdb
```
