### ISSUE TITLE
node.querySelectorAll is not a function in 1.10.0

### ISSUE THREAD

**Issue by thewilkybarkid** [observablehq/framework#1559]
We've just upgraded from 1.9.0 to 1.10.0, and our inputs are now broken with a `node.querySelectorAll is not a function`, coming from:

https://github.com/observablehq/framework/blob/c5d57f7b4bec45c7081add57ccfba3a8d0e34d11/src/client/main.js#L179

I've only quickly looked into it, but it seems to be getting all DOM nodes, not just elements.

**Comment by mbostock** [comment]
Hmm. This might occur if you are displaying non-elements such as text nodes or comments. I’ll investigate.

**Comment by mbostock** [comment]
Apologies for this obvious crash. I’ve pushed a fix and we’ll release 1.10.1 shortly (once #1557 lands).

**Comment by mbostock** [comment]
Fixed in #1561.
