### ISSUE TITLE
Cannot read properties of undefined (reading 'previousSibling') when accessed from CF Pages custom domain

### ISSUE THREAD

**Issue by adityawarmanfw** [observablehq/framework#1586]
When deploying to CloudFlare Pages and accessing via custom domain, it gives the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'previousSibling')
    at findLoading (client.e1b67211.js:1:11651)
    at define (client.e1b67211.js:1:9134)
    at <anonymous>:10:1
```

However, the site is working fine in pages.dev and dev preview (`npm run dev`).

CF Pages: https://moonboard-3od.pages.dev/exploration/versions
Custom domain: https://moonboard.adityawarmanfw.id/exploration/versions

**Comment by mbostock** [comment]
If you compare the source of the two pages, you will see that on the custom domain, Framework’s placeholder comment has been stripped:

```
<!--:fa94b826:-->
```

This comment is needed for Framework to know where to insert dynamic content. You probably have a feature enabled on your Cloudflare Pages that is stripping comments to minimize the page. You will need to disable this feature to prevent Cloudflare from corrupting your site.
