### ISSUE TITLE
Add version badge for reference to file.size

### ISSUE THREAD

**Issue by gvanhorne** [observablehq/framework#1640]
From the docs here: https://observablehq.com/framework/files#static-analysis it would appear users can check for missing files using `file.size`.

From [this commit](https://github.com/observablehq/framework/commit/06ed740f7803df18f46cfd6b23d6601cb9409e1b) it looks to me that file.size is always undefined for versions < `1.11.0`. As such, it may be appropriate to add a version badge to the documentation here so as to prevent developers mistakenly using the `file.size` attribute when it will always be undefined for older versions.

**Comment by mbostock** [comment]
Yes, it’s mentioned above where it says “size in bytes” but we could repeat it.

**Comment by Fil** [comment]
We usually don't repeat version badges. Is this to be treated as a special case? An alternative could be to link the term to its definition.

**Comment by gvanhorne** [comment]
It makes sense to me now in the context of the entire page (knowing that "size in bytes" refers to the same feature). This came up during development for me as I only read the https://observablehq.com/framework/files#static-analysis section of the page, and it took a brief moment to debug. Totally optional issue but I thought it might save some future grievances (albeit minor)!
