### ISSUE TITLE
github pages failing to render static build

### ISSUE THREAD

**Issue by bjedwards** [observablehq/framework#1643]
Using observable framework to build a static site to deploy to github pages.

Repo is here https://github.com/bjedwards/vuln4cast_presentation

Deployed to github pages here:

https://bjedwards.github.io/vuln4cast_presentation/

For whatever reason, github cannot serve the css or js files, and they all 404.

![image](https://github.com/user-attachments/assets/678a9fab-2345-428c-91f8-2a87566af685)

And of course that means the site doesn't render:

![image](https://github.com/user-attachments/assets/71b63f31-89ec-403f-a6ca-f5a973758b5f)

My local build works fine, with the static site displaying for two server types (`python -m http.server` and `npx http-server dist`). Is this a github pages issue or a framework issue?

**Comment by mbostock** [comment]
You need to add a `.nojekyll` file as mentioned in the docs.

**Comment by bjedwards** [comment]
Beautiful, thank you. I missed that bit.
