### ISSUE TITLE
do we need an explicit <head> ?

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1656]
I wanted to use Google Webmaster Tools on [pangea](https://observablehq.observablehq.cloud/pangea/), and tried to verify ownership with a meta

```
<meta name="google-site-verification" content="iWyKAa-v6tF3VF9SMInpGS-PVBcJsy4v5p08VyKAkI4">
```

but I got:

```
Ownership verification failed
Verification method:
HTML tag
Failure reason:
Your meta tag is not in the <head> section of your home page.
Please fix your implementation and reverify, or use another verification method.
```

Maybe if we had an explicit `<head>…</head>` this would not occur.

**Comment by mcmcclur** [comment]
Yes - absolutely! 

For that matter, there should be explicit `html` and `body` elements and you might consider what options to support. At a minimum, the `html` element should support the option to specify the language:

    <html lang="en">

Though, you might prefer `lang="fr"`. :)
