### ISSUE TITLE
Custom domains for Observable Cloud data apps

### ISSUE THREAD

**Issue by jamesking** [observablehq/framework#1674]
I would like to use Observable Framework to publish a site. 

I would like to use Observable Cloud for this, but I want a custom domain. Is this in the roadmap in the near future?

**Comment by ananya-roy** [comment]
Hi James  👋
This feature is available today in our [Enterprise tier](https://observablehq.com/pricing). Please reach out at support@observablehq.com and we can talk through the process of enabling this for your workspace.

Thanks!
