### ISSUE TITLE
case sensitive page URLs

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1683]
Like https://github.com/observablehq/framework/issues/1367 but for pages. Suppose I have a path/to/page.md, and link to `[link](/PaTh/To/PaGe)`. It works in preview if I'm using a case-insensitive dev machine, but will fail in prod if the server is case-sensitive. (The opposite configuration might create a bug too, but I believe it's less common.)

(Reported by https://github.com/mcmcclur/MarkOnFramework/discussions/5.)

Not sure how to address this one. The solution cannot be the same as #1374: the difference being that, for files, both links and paths are generated from the markdown contents (so we can spot a discrepancy if two references to the same file point to different casings that end up at the same place on disk). For pages, the paths are generated from the src folder, and the links from the markdown contents.

🤔

**Comment by mbostock** [comment]
Doesn’t this fall under broken link detection #363? If we validate links, we can do a case-sensitive check. But currently we don’t validate links to pages at all. Close this as duplicate?

**Comment by Fil** [comment]
duplicate
