### ISSUE TITLE
Runtime error on mobile browsers (Iphone 14 plus, Iphone 11)

### ISSUE THREAD

**Issue by yugin-pro** [observablehq/framework#1707]
Created report using mermaid and duck db. It is working well on desktop chrome and firefox latest version for both dev and prod.
But when i want to open report on cell phone I been getting several errors
- **_Runtime error : unexpected token {_**  - does not show mermaid diagramm
source code : `
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  import {svg, html} from "npm:htl";

    mermaid.initialize({
    securityLevel: 'loose',
    theme: 'dark',
    });

  mermaid.registerIconPacks([
  {
    name: 'logos',
    loader: () =>
      fetch('https://unpkg.com/@iconify-json/logos/icons.json').then((res) => res.json()),
  },
]);

  const drawDiagram = async function (graph) {
    const id = 'r-' + Date.now()
    let element = html`<div class='customMermaidBlock'></div>`
    const { svg } = await mermaid.render(id, graph);
    element.innerHTML = svg
    return element;
  };`

- **_Runtime error : import.meta.resolve is not a function_**  - does not show duckdb req and tables

report prod is here https://e-commerce-analytics-4b24a.web.app/development/architecture.html

**Comment by mbostock** [comment]
First, we recommend [importing Mermaid](https://observablehq.com/framework/lib/mermaid) using an `npm:` import so that it is self-hosted:

```js
import mermaid from "npm:@observablehq/mermaid";
```

Second, you can use the built-in `mermaid` tagged template literal to use Mermaid rather than needing to call `mermaid.render` yourself.

Lastly, `import.meta.resolve` requires [a recent browser](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve#browser_compatibility); see [Can I use](https://caniuse.com/?search=import.meta). It looks like iOS 16.4 or later is required. Possibly we could transpile the code to use `import.meta.url` instead of broader compatibility. I’ll open a feature request.

**Comment by mbostock** [comment]
It worked for me. 🤷 Here’s what I wrote, only minor tweaks to your code:

```js
import mermaid from "npm:mermaid";

mermaid.initialize({
  startOnLoad: false,
  securityLevel: "loose",
  theme: "dark"
});

mermaid.registerIconPacks([
  {name: "logos", loader: () => fetch("https://unpkg.com/@iconify-json/logos/icons.json").then((res) => res.json())}
]);

let nextDiagramId = 0;

const drawDiagram = async function (source) {
  const root = document.createElement("div");
  root.innerHTML = (await mermaid.render(`mermaid-${++nextDiagramId}`, source)).svg;
  return root.removeChild(root.firstChild);
};
```

You could try clearing your `.observablehq/cache/_npm` if you maybe have an old version of Mermaid installed.

**Comment by yugin-pro** [comment]
I deleted cash and put this code
`
```js

import mermaid from "npm:mermaid";

mermaid.initialize({
  startOnLoad: false,
  securityLevel: "loose",
  theme: "dark"
});

mermaid.registerIconPacks([
  {name: "logos", loader: () => fetch("https://unpkg.com/@iconify-json/logos/icons.json").then((res) => res.json())}
]);

```

```mermaid
architecture-beta
    group api(logos:aws-lambda)[API]

    service db(logos:aws-aurora)[Database] in api
    service disk1(logos:aws-glacier)[Storage] in api
    service disk2(logos:aws-s3)[Storage] in api
    service server(logos:aws-ec2)[Server] in api

    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
```  
`
unfortunately i have same error **_TypeError: mermaid is not a function_** Apparently, i should clean my carma, but i don't know where is the cache 😁

Thanks for rewriting drawDiagram() - now I use it and its working well
