### ISSUE TITLE
4-column grid rendered as 2 columns with 1.12.0

### ISSUE THREAD

**Issue by happz** [observablehq/framework#1709]
I noticed on my site first, after updating to 1.12.0 the following HTML rendered as two cards, the latter below the former:

```html
<div class="grid grid-cols-4">
  <div class="grid-colspan-3 card game-summary">${render_game_summary(game)}</div>
  <div class="card">${render_game_report_legend()}</div>
</div>
```

Developer tools in the browser also showed just two columns in the grid. Before the update, cards were rendered on the same row, 3+1 easily fitting into 4 columns.

And while I'm not 100 % sure I remember it correctly, I think the same is happening in framework docs: check the attached picture, wasn't this a 4-column grid, as suggested by the example HTML below? No change of browser window or font led to 4 cards landing on the same row of the grid.

![2024-10-02_00-28](https://github.com/user-attachments/assets/7b2ca568-bd64-47c5-9467-ff1bf0b9875f)

After reverting to 1.11.0, I got back the "3-column card and 1-column card on the same row" behavior in my site.

**Comment by mbostock** [comment]
With the fix in 2ff8c4a and adding 

---
toc: false
---

and removing ~1rem of padding somewhere, we could make 4 columns fit…
