### ISSUE TITLE
bracketed parameter name as a parameter value

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1760]
Suppose you have `src/[param].md`

* opening http://127.0.0.1:3000/[foo] shows the page parameterized with param=[foo]. ⁽ᶠᶦˣᵉᵈ· ʷᵃˢ ᵖᵃʳᵃᵐ⁼ᶠᵒᵒ⁾
* opening http://127.0.0.1:3000/[param] shows the non-parameterized page

If dynamicPaths contains `"/[foo]", "/[param]"`, the first page is generated as a parameterized page, the second as a normal page. 

Definitely a corner case, but this feels inconsistent. We should probably prioritize routing to the parameterized page?

**Comment by mbostock** [comment]
Feels like an edge case, but seems reasonable to change the routing so that `[param]` is treated as a parameter value instead of an exact match. If you have a parameterized page you shouldn’t expect it to be invoked without its parameters.
