### ISSUE TITLE
Allow verbose URLs from home - `/index.html`

### ISSUE THREAD

**Issue by aaronkyle** [observablehq/framework#1782]
In certain hosting environments, clean URLs can be tricky to implement.  Enabling a verbose Framework home URL at `project-url/index.html` would enable a solution within the Framework context (i.e. without having to re-configure server redirects).

Note the AWS S3 bucket use case, where a bucket that is not configured to host static URLs could be used to deploy Framework projects if this feature were enabled.

**Comment by Fil** [comment]
duplicate of #1781 :)
