### ISSUE TITLE
avoid nested logs?

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1788]
Some logs are nested, resulting in a duration timestamp that we don't necessarily know how to associate with the action.

example (when building pangea):
![Image](https://github.com/user-attachments/assets/60c5bb5d-40fd-4d65-b39a-9f50b1f03f1a)

this happens (typically? or only?) when a page triggers a module download

Maybe this needs a clack [spinner](https://github.com/bombshell-dev/clack/tree/main/packages/prompts#spinner) that resolves when the action is completed?

relevant places:

https://github.com/observablehq/framework/blob/b66e15252055ca5cf6b55aaf24129c3809de63eb/src/build.ts#L90

https://github.com/observablehq/framework/blob/b66e15252055ca5cf6b55aaf24129c3809de63eb/src/build.ts#L116

It's not a major inconvenience, though.

**Comment by mbostock** [comment]
This occurs when operations occur in parallel. Parallelizing is very useful for making things faster, but would require additional effort if we also want the logs to be readable.

**Comment by Fil** [comment]
We haven't yet really tried to parallelize the builds. This issue is about when building a file needs building one or several other files.

Typically

```
load /theme/dark load /theme/dark.md → [fresh] success 3.42 kB in 2ms
in 19ms
```

should be understood as
```
load /theme/dark
>  load /theme/dark.md → [fresh] success 3.42 kB in 2ms
in 19ms
```

and similarly we have
```
load /lib/arquero npm:arquero@latest → npm:arquero@7.1.0
npm:arquero@7.1.0/+esm → docs/.observablehq/cache/_npm/arquero@7.1.0/_esm.js
npm:arquero@7.1.0/package.json → docs/.observablehq/cache/_npm/arquero@7.1.0/package.json
npm:acorn@^8.12.1 → npm:acorn@8.14.0
npm:@uwdata/flechette@^1.1.0 → npm:@uwdata/flechette@1.1.1
npm:acorn@8.14.0/+esm → docs/.observablehq/cache/_npm/acorn@8.14.0/_esm.js
npm:@uwdata/flechette@1.1.1/+esm → docs/.observablehq/cache/_npm/@uwdata/flechette@1.1.1/_esm.js
in 730ms
```

which could be reformatted as
```
load /lib/arquero
> npm:arquero@latest → npm:arquero@7.1.0
> > npm:arquero@7.1.0/+esm → docs/.observablehq/cache/_npm/arquero@7.1.0/_esm.js
> > npm:arquero@7.1.0/package.json → docs/.observablehq/cache/_npm/arquero@7.1.0/package.json
> > npm:acorn@^8.12.1 → npm:acorn@8.14.0
> > npm:@uwdata/flechette@^1.1.0 → npm:@uwdata/flechette@1.1.1
> > npm:acorn@8.14.0/+esm → docs/.observablehq/cache/_npm/acorn@8.14.0/_esm.js
> > npm:@uwdata/flechette@1.1.1/+esm → docs/.observablehq/cache/_npm/@uwdata/flechette@1.1.1/_esm.js
in 730ms
```


(it feels hard to fix this, since we're using the `sdtout` Writer directly; not planning to spend more time on it.)

**Comment by mbostock** [comment]
> We haven't yet really tried to parallelize the builds.

I think even during build, Rollup runs our `importResolve` plugin in parallel, which explains what we’re seeing here.
