### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by felippecaso** [observablehq/framework#1795]
Using Deno v2.0.4 (MacOS 15.1, zsh), when initializing a new project and including sample files, the `Example dashboard` is broken due to not loading `launches.csv` correctly:

![Image](https://github.com/user-attachments/assets/6b9e1241-19ff-4e2d-bb1b-afb7724764a3)

In the CLI, the error is

```
GET /_file/data/launches.csv?sha=<redacted>
load /data/launches.csv → [missing] error in 0ms: tempFd.createWriteStream is not a function
TypeError: tempFd.createWriteStream is not a function
    at file:///Users/usrname/foldername/node_modules/.deno/@observablehq+framework@1.12.0/node_modules/@observablehq/framework/dist/loader.js:383:34
    at eventLoopTick (ext:core/01_core.js:175:7)
```

## Steps to reproduce
- Initialize a new project with `deno run -A "npm:@observablehq/framework@latest" create`;
- Choose `Yes, include sample files` and _do not_ install dependencies;
- `cd` into the chosen folder;
- `deno install`
- `deno task dev`

**Comment by Fil** [comment]
Confirmed. What's surprising is that when I log the `tempFd` symbol it is a `FileHandle`, and it should support `createWriteStream`:
https://docs.deno.com/api/node/fs/promises/~/FileHandle.createWriteStream

Note that we don't officially support deno, so not really a bug :) But it would be nice to fix nonetheless.

**Comment by Fil** [comment]
minimal repro:

```
❯ cat test.js
import {open} from "node:fs/promises";
const a = await open("test.js", "r");
console.warn(a.createWriteStream);
```

with Node:
`[Function: createWriteStream]`

with deno 2.0.6:
`undefined`

this is a bug with deno, I'm afraid?
