### ISSUE TITLE
jQuery UI found by keyword search

### ISSUE THREAD

**Issue by malcook** [observablehq/framework#1801]
I stumbled across the [jQuery UI documentation page](https://observablehq.com/framework/lib/jquery-ui#j-query-ui) while searching for "stylesheet", as pictured:

![Image](https://github.com/user-attachments/assets/dec3ff5a-dba5-4850-82f6-391ecacd01b8)

I expect the root cause is the same as #1264 which was closed as a working as expected.

I think you might reconsider.  It is a rather confusing user experience for pages like this to only be reachable by keyword search.

**Comment by mbostock** [comment]
These aren’t libraries that we expressly recommend, even though we are providing examples of how to use them for those who actively seek them out.
