### ISSUE TITLE
Dark mode toggle

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#182]
Should we support a dark mode toggle, like some sites do? It’s a bit redundant given that you can control it via system preferences, and that we automatically chose the default mode based on your system preferences, but it’s nice if the user wants to change it quickly I suppose.

**Comment by mbostock** [comment]
Apple [explicitly advises against this](https://developer.apple.com/design/human-interface-guidelines/dark-mode#Best-practices):

> **Avoid offering an app-specific appearance setting.** An app-specific appearance mode option creates more work for people because they have to adjust more than one setting to get the appearance they want. Worse, they may think your app is broken because it doesn’t respond to their systemwide appearance choice.

**Comment by Fil** [comment]
Should we disable it in our vitepress docs too? https://github.com/observablehq/plot/issues/1955

Also, it makes sense to avoid this distraction for viewers, but I'm still looking for ways to surface _to the developer_ that they have to think about the two presentations.
