### ISSUE TITLE
Update places to find support

### ISSUE THREAD

**Issue by bbkane** [observablehq/framework#1826]
I found the Slack first, where the welcome bot says to ask in #help:

![Image](https://github.com/user-attachments/assets/331f5374-b5a1-48e2-97d6-6ed22bf11dee)

However, the #help channel is archived, with a message saying, go to the forum:

![Image](https://github.com/user-attachments/assets/09dd6095-cb88-4876-9f35-0f77273db5f4)

Then I was browsing the forum, and [a post I came across](https://talk.observablehq.com/t/getting-tabulator-to-work-in-framework/9997/2) says to go to GitHub discussions for help?

![Image](https://github.com/user-attachments/assets/a733d98f-ef70-4841-8079-6ce8da66afb4)

Is there a list somewhere of which area is appropriate for which questions/discussions?

**Comment by mootari** [comment]
Thanks for letting us know! We've updated the personal Slack welcome message.

We'll also soon have better guidance within the forum so that people can learn about our support channels more easily before they create a new topic.
