### ISSUE TITLE
Framework v1.13 building a broken version of React 19

### ISSUE THREAD

**Issue by sbarre** [observablehq/framework#1866]
I'm opening an issue because I think I've found a bug while debugging [an issue with my own work](https://github.com/observablehq/framework/discussions/1865) on the discussion forum.

Here are my steps to reproduce:

I installed a fresh version of Framework 1.13 using `npx @observablehq/framework@latest create`.

I created a super simple JSX component in `components/Button.jsx`:

```jsx
import * as React from "npm:react";

export default function Button() {
  return (
    <button>Test</button>
  )
}
```

I import and add this button to the existing `index.md` file:

```js
import Button from './components/Button.js';

display(<Button />)
```

The above `display()` call is in a fenced `jsx` block, sorry I don't know how to display that properly in here.  

Anyways, then I run `npm run dev` and load the homepage, and the button does not appear.  

I see this error in the browser console:

```
Uncaught (in promise) TypeError: createRoot is not a function at client.js:211:19
```

And sure enough in the client.js bundle it's importing the `_npm/react-dom@19.0.0` library but that file does not export a method called `createRoot`..  

Now, if I look in the `.observablehq/cache/_npm` folder I see that the `react-dom@19.0.0` folder contains one file:  `_esm.js` and that file is only 4,492 bytes.   

The same file in a previous Framework v11.1 project, for `react-dom@18.3.1` is around 192k ...  Plus there are other files in that folder including a `package.json` etc..  Those other files are not present here in v1.13

Similarly the `_esm.js` file in the `cache/_npm/react@19.0.0` folder seems suspiciously small as well (11k)..   

This is all from a fresh vanilla install with no other changes except creating a basic JSX component to test.

I'm on a Mac (Sequoia 15.1.1) and I'm running Node 20.11.1

**Comment by sbarre** [comment]
To rule out machine-specific issues, I also performed the same steps above in Ubuntu on a different computer and got the same results.

**Comment by mbostock** [comment]
React has had a broken (incompatible with ES modules) distribution for quite some time https://github.com/facebook/react/issues/11503, so we had to do a clunky workaround to get esbuild to convert it into a functional ES module:

https://github.com/observablehq/framework/blob/8efdcf45c00f7cb471deab01f65fe93e1b539d44/src/node.ts#L75-L87

It’s possible that they’ve changed something that will require us to do another workaround to get React 19 to work. It’s not a bug in Framework per se, but we’re willing to make changes to get React working again.

**Comment by sbarre** [comment]
For what it's worth I tried pinning `@18` in my test and I see the same issue, so it might be all builds?  

Anything I can do to debug this further?

**Comment by mbostock** [comment]
I don’t think pinning React using `import * as React from "npm:react@18"` will work because there’s an implicit unpinned import that is generated when you use JSX. You might be able to get it to work by clearing your npm cache and then creating the appropriate folders, something like:

```sh
rm -rvf docs/.observablehq/cache/_npm
mkdir -p docs/.observablehq/cache/_npm/react-dom@18.3.1
mkdir -p docs/.observablehq/cache/_npm/react@18.3.1
```

**Comment by sbarre** [comment]
Thanks for that workaround!  I can confirm that it works for me as well.  

I inserted some extra commands in my Dockerfile to create those paths after `git checkout` and `npm install` and before `npm run build`.

**Comment by ifree** [comment]
Unfortunately I'm unable to get it working with the workaround above, is there a way to blacklist React 19 or pin to the previous version?

**Comment by caseyg** [comment]
Thank you for the quick fix! Is it possible to push a patched minor version to NPM so that CI builds which pull in the `@observable/framework` package can use this? Thank you!
