### ISSUE TITLE
Publish minor version of @observable/framework with React patch to NPM to fix CI builds

### ISSUE THREAD

**Issue by caseyg** [observablehq/framework#1878]
Thank you for the quick fix #1872! Is it possible to push a patched minor version to NPM so that CI builds which pull in the `@observable/framework` package can use this? For now my builds using the NPM latest are unable to display React components. Thank you! 

(_Originally posted by @caseyg in [#1866](https://github.com/observablehq/framework/issues/1866#issuecomment-2530282476)_)

**Comment by mbostock** [comment]
We’ll publish when we can. We don’t need a tracking issue for the next release.
