### ISSUE TITLE
investigating: slow S3 proxying

### ISSUE THREAD

**Issue by srenatus** [observablehq/framework#1884]
Heya!

Thanks again for OF, I like using this a lot. ✨ 

I've got a problem, though, with serving the reports from S3. We're using a proxy that does the corp's authentication, and then services the requests by retrieving and forwarding the files from S3 (using Caddy + https://github.com/sagikazarmark/caddy-fs-s3). It works pretty well, in general, but fetching a 12MB duckdb database is taking surprisingly long -- it's basically trickling in:

<img width="902" alt="Image" src="https://github.com/user-attachments/assets/c60466e8-718b-4ab7-b9d2-f728237e605f" />

This makes the overall report viewing feel quite sluggish:
<img width="413" alt="Image" src="https://github.com/user-attachments/assets/94627e8e-88bc-48bf-8f32-1467fd0dff31" />

Now, I don't know where to start. My first hunch is that if it just fetched the file at once, it would probably perform better -- I know that duckdb does range-requests, but in this case, I'd like to opt-out if possible. Relatedly, I don't know if this really is an OF problem or a duckdb-wasm one. I don't think it's go to do with our proxying setup, I can curl the entire file (through the proxy) in ~0.12s.

If you've got any hints to share, I'd appreciate it. Maybe I'm missing something very basic here 😳

**Comment by mbostock** [comment]
This sounds like it was fixed in https://github.com/observablehq/framework/pull/1734/commits/7704416cf65daae854784093b7d9e93d051f9a1b (#1734). What version of Framework are you using? Or are you explicitly asking DuckDB to create a view instead of a table?

**Comment by srenatus** [comment]
I'm on the latest release,
```
└── @observablehq/framework@1.13.0
```

But your snippet is useful -- it's [starting with a check for .parquet](https://github.com/observablehq/framework/commit/7704416cf65daae854784093b7d9e93d051f9a1b#diff-df4f4854fd9489c8532e64f9f86253e604522e99d7223b010c77494929fd1fcdR284) and I am using a duckdb "db file" which I've put into the preamble as
```yaml
---
toc: true
sql:
  thisthing: ./data/thisthing.db
---
```

I don't suppose I can use parquet files there, can I? :bulb: [I most certainly can.](https://observablehq.com/framework/sql) And I've only got one table in each db file anyways, so there's nothing lost. 🥳 

Then this is what I'll be trying next. Thanks a bunch! I think this is most likely resolved, I'll reopen and come back here if it's not.

**Comment by mbostock** [comment]
Maybe we should increase the default block size for the `ATTACH` statement, or allow it to be customizable.

**Comment by srenatus** [comment]
Yep, this looks better now:

<img width="911" alt="Image" src="https://github.com/user-attachments/assets/1cf11ccf-2bf3-4e1c-bbf1-2f6710c8689d" />

In summary:

<img width="408" alt="Image" src="https://github.com/user-attachments/assets/f61bb329-2883-4874-8832-3691643e9be0" />

Thanks again!
