### ISSUE TITLE
Timestamp in frontmatter title field renders as new Date() in pager

### ISSUE THREAD

**Issue by df-rw** [observablehq/framework#1887]
Two `.md` files in the same directory with this frontmatter:

```md
---
title: 2024-12-19
---
```

```md
---
title: 2024-12-20
---
```

renders the pager on the appropriate page as:

* <img width="325" alt="Image" src="https://github.com/user-attachments/assets/486e3494-019f-447e-b5b8-795bb503f1b7" />
* <img width="316" alt="Image" src="https://github.com/user-attachments/assets/cf1be695-b846-45eb-abfb-d6ff7958c700" />

🤔 couldn't see anywhere in the docs any mention of transform. Wondering if this is expected behaviour?

**Comment by df-rw** [comment]
And sidebar as well:

<img width="268" alt="Image" src="https://github.com/user-attachments/assets/4add217b-d6ba-4bc9-bd63-9c3cf00623fc" />

**Comment by mbostock** [comment]
I think you need to put quotes around it so that YAML interprets it as text rather than a date.

**Comment by df-rw** [comment]
🤦 Thanks @mbostock
