### ISSUE TITLE
JSX/React and styled components broken

### ISSUE THREAD

**Issue by ian-leggett** [observablehq/framework#1889]
Hey Observable team,

I recently re-built my project which I have been working on for a few weeks only to find that React blows up after clearing the cached packages. I know this issue was raised the other day and the culprit is a recent release of React but I wanted to expand on the[ issue that was recently closed](https://github.com/observablehq/framework/issues/1866#issue-2721487479) as I think there is more to it. Currently the [only work around](https://github.com/observablehq/framework/issues/1866#issuecomment-2521599471) is a bit of a hack which was kindly commented by @mbostock (a big thank you for this by the way). 

Why does the Observable framework pull the latest and greatest version of React even if you are running v1.9.0 which was when you first introduced JSX/React? Shouldn’t this have pinned a version of React that currently worked at the time? Surely by always consuming the latest you introduce a ticking time bomb where a major release will at some point kill your codebase. I also wanted to mention that although the current fix works and allows us to continue with React I now have an issue with styled components which was working perfectly before. I am finding it very hard to debug what the issue is with styled components so I can’t really post anything useful at the moment. Rather than fight with styled components I just ripped it out and changed the way I style the JSX. I am sure you guys are looking into this at the moment but will you consider pinning versions of React in the future? If you have time please try installing styled components too and see if you can work with it. Thanks for reading and any info or advice going forward would be great.

**Comment by mbostock** [comment]
The issue has been fixed in the main branch (hence the issue closing) but we have not yet published a new release. You’ll need to wait until the release comes out, or build from main. Hopefully soon.

**Comment by ian-leggett** [comment]
Thats great thanks @mbostock 👍
