### ISSUE TITLE
Use hashed names to ensure cache-breaking on deploy

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#260]
This should apply to:

- file attachments
- imported modules
- framework code (e.g., style.css, client.js)

**Comment by mbostock** [comment]
This will be mostly fixed by #843, but there are a few caveats: it doesn’t include Framework’s own code (yet), and the content hash is in the query string which isn’t as good as putting it in the file name. But maybe I could incorporate that into the PR, too.

**Comment by Fil** [comment]
> isn’t as good

Having the hash in the query string also has some benefits. For example, supposing I'm exposing a data file to be consumed by an external process, how would that external process now have access to the (changing) file name, if it includes the hash? Should we also publishing a mapping manifest somewhere?

**Comment by mbostock** [comment]
> Should we also publishing a mapping manifest somewhere?

At least in the case of `FileAttachment` the original name will still be present as `file.name`. Only the `file.url` is affected by the content hash (and diffferent serving location under `_file`).

**Comment by Fil** [comment]
What I mean is that a website is not always an island, and files can be an "api" entry point for another service (maybe the website has a file "output" that is read by a rss reader?). Not having predictable/stable URLs could make some potential use cases more difficult.

**Comment by mbostock** [comment]
I think it’s a non-goal for served assets to have a public API. It’s an implementation detail and we reserve the right to change it over time. If people want a public API for for assets then they should manage it themselves say using a public assets folder (which we expressly avoided in #169, but you can always add to `dist` after building).

**Comment by Fil** [comment]
Makes sense, but it's good to be explicit about this ;-)

**Comment by mbostock** [comment]
Fixed in #843.
