### ISSUE TITLE
Interpolation with .map within HTML inserts parent <span> element

### ISSUE THREAD

**Issue by cinxmo** [observablehq/framework#446]
In an .md file:
~~~
```js
const testArray = ['a', 'b', 'c'];
```

```js
function formatLetter(letter) {
	return html`
		<div>
			${letter}
		</div>
	`;
}
```

<div>
	${testArray.map((t) => formatLetter(t))}
</div>
~~~

Notice that each of the `<div>${letter}</div>` blocks are wrapped around a span element:
<img width="271" alt="Screenshot 2024-01-05 at 5 15 48 PM" src="https://github.com/observablehq/cli/assets/37343722/57f4b49a-b2e4-4530-9078-faaee4bf3e42">

Should this be the case?

**Comment by net** [comment]
Is this documented somewhere? It comes up when you're interpolating table rows since the wrapping spans break the table, and it took me some time before I found this issue.
