### ISSUE TITLE
Detect broken socket and reconnect automatically

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#50]
If the socket closes, the client never tries to reopen and reconnect.

**Comment by code-SL** [comment]
Note that in neovim, `set backupcopy=yes` needs to be set or else socket is closed upon save. Emacs doesn't seem to exhibit the same problematic default setting that closes upon save.

**Comment by Fil** [comment]
related #563

**Comment by eitanlees** [comment]
Thank you @code-SL for the neovim solution!

I added the following to `~/.config/nvim/init.lua` 

```
vim.opt.backupcopy = 'yes'
```

and that alleviated the issue.
