### ISSUE TITLE
Automatic summary table display for tabular data?

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#52]
Related to custom inspectors #51, we could automatically detect tabular data and give a better default display using the summary table #23.

**Comment by mbostock** [comment]
SQL cells use `Inputs.table`. But it would be nice to have column summaries.

**Comment by Fil** [comment]
SQL cells have the added benefit that we can use the SQL engine to create the histograms (and other summaries), and (later) the filtering.

**Comment by mbostock** [comment]
Given that was have SQL cells using `Inputs.table`, I think this issue is basically covered by #23 — we’ll switch SQL cells to use that when it’s ready, and we’d have a programmatic way of getting the same display from JavaScript if desired. But I don’t think we’ll do “automatic display modes” where we change the behavior of the default inspector.
