### ISSUE TITLE
Add rel="noreferrer" to external links by default

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#53]

**Comment by Fil** [comment]
I'm not sure why we should do this, and then should some of this be optional?

**Comment by mbostock** [comment]
The reason to do the `noreferrer` is privacy by default: if you leak a referrer, you may reveal information about the linking data app to an untrusted third party, including the origin, path, and query string.

The reason to do `nofollow` and `noindex` would be to mitigate SEO spam on public projects. I’m not sure we need to do this, and it’s definitely not a priority.

**Comment by Fil** [comment]
Thanks for the explanation; I feel it's right to leave nofollow out of this, as it would "punish" everyone; on some sites only the recently-created users get this treatment, as a conservative measure against spammers, but not established users.
