### ISSUE TITLE
Backslashes aren’t unescaped within PRE elements

### ISSUE THREAD

**Issue by mbostock** [observablehq/framework#636]
Consider the following HTML:

```html
<pre>${test}</pre>
```

The `${test}` is interpreted as a live expression, so if `test` is not defined, you’ll see an error:

```
RuntimeError: test is not defined
```

You can prevent the live expression using a backslash:

```html
<pre>$\{test}</pre>
```

However, the resulting backslash is still rendered in the output, producing:

```
$\{test}
```

A workaround is to use `&dollar;` instead:

```html
<pre>&dollar;{test}</pre>
```

This is probably something we should fix in #597.

**Comment by Fil** [comment]
There is also `<pre>$&zwj;{test}</pre>` (I know, not a very helpful comment!)
