### ISSUE TITLE
Examples aren’t deployed to Observable

### ISSUE THREAD

**Issue by mythmon** [observablehq/framework#643]
When deploying the site, we use two different approaches for Cloudflare Pages and Observable Cloud. The process for Cloudflare Pages runs `yarn build`, modifies the resulting dist file, then uploads the entire thing to Cloudflare. The process for Observable Cloud uses `observable deploy`'s internal build command, which does not provide any chance to add extra file to the upload.

I can think of a few ways this could be dealt with:

0. Don't do anything, and leave the docs on Cloudflare pages.
1. Integrate the examples directly into the project instead of as outside examples.
2. Add some sort of "post build" action support to Framework that gives us a chance to add those files by running a command.
3. Have some sort of "public" directory. Everything inside that folder would get included in builds, both normal and deploy.

There are probably other ways around it too

**Comment by Fil** [comment]
decoupling PR #1042

**Comment by Fil** [comment]
After #1306 I think this is now complete?
