### ISSUE TITLE
Nits on getting-started.md

### ISSUE THREAD

**Issue by mcglincy** [observablehq/framework#715]
Nits on getting-started:

- The code snippet for `temperaturePlot(forecast)` is missing a trailing semi-colon, which we show elsewhere

- does the frontmatter theme have to appear at the top of the file? And if so should we mention that in the text? (the side by side screenshot does show it on top, above the h1)

- "Deploy messages can be set using yarn deploy --message." Should we prefer example commands use npm?

**Comment by mbostock** [comment]
I think these are mostly fixed?
