### ISSUE TITLE
During deploy, if a file is larger than the limit, don't try to upload it

### ISSUE THREAD

**Issue by mythmon** [observablehq/framework#718]
The limit is 50MB currently. We may want to have a way to ask the server what the limit is instead of hard coding it.

**Comment by Fil** [comment]
This works well now; the error message is informative but the "no details" part is surprising:

```
◐  Sending file manifest to server│
■  The server rejected some files from the upload:
│
│    - _file/bigfile.60fafc9d.mp4 - (File size of 984 MB exceeds maximum of 50.0 MB)
│
■  Error: Server rejected deploy manifest: no details
```

**Comment by mbostock** [comment]
Seems like we could close this (and maybe file a follow-up issue for the “no details” part)?
