### ISSUE TITLE
Things break when a file name contains emoji

### ISSUE THREAD

**Issue by dunstan** [observablehq/framework#783]
I put an emoji in the filename and the preview of the emoji page rendered but the command line wasn't happy. I was also able to deploy it, but when I tried to view the emoji page on staging I got a "not found" error.

What do we think should happen here? Is this a bug?

<img width="1032" alt="Screenshot 2024-02-13 at 15 26 40" src="https://github.com/observablehq/framework/assets/1316196/dade147e-7bbe-4884-8a13-da815fc5d338">
<img width="1112" alt="Screenshot 2024-02-13 at 15 27 29" src="https://github.com/observablehq/framework/assets/1316196/8392eae0-7785-4362-9188-68aeed8ef1e1">

![Screenshot 2024-02-13 at 15 26 35](https://github.com/observablehq/framework/assets/1316196/a5df91e9-dbb7-42eb-a2bc-f023187d5118)

![image (20)](https://github.com/observablehq/framework/assets/1316196/44c60e6e-c5b3-4a60-a8a3-88adcf05296f)

@Fil [also notes that he can put a < character in a file name](https://observablehq.slack.com/archives/C05UDG0BRDY/p1707866315692459).

**Comment by Fil** [comment]
related #778
