### ISSUE TITLE
document example data sets

### ISSUE THREAD

**Issue by trebor** [observablehq/framework#817]
the [example data sets](https://github.com/observablehq/stdlib/blob/6ad71d98c4362d71e086fd5a0b5f97128cb9d906/src/library.js#L61-L72) defined in [stdlib](https://github.com/observablehq/stdlib) are available in `framework` but not documented, as pointed out in [this post](https://talk.observablehq.com/t/observable-framework-where-did-penguins-come-from/8792).  i'm not sure exactly where these would fit in the structure, but they do seem like a good thing to add.

~~i think [this notebook](https://observablehq.com/@observablehq/sample-datasets) is the most canonical documentation for the list.~~

https://github.com/observablehq/sample-datasets

**Comment by Fil** [comment]
refs:
- #371
- #373
- #401
