### ISSUE TITLE
Documentation not working on Firefox 117.0.1

### ISSUE THREAD

**Issue by Minnozz** [observablehq/framework#828]
Interactive elements are stuck on a loading spinner:
![image](https://github.com/observablehq/framework/assets/701386/9c7f4bb3-ec26-4333-9a8b-838b20c8f5ec)

Possibly caused by this error?
```
Uncaught DOMException: Document.querySelectorAll: '#observablehq-main h1:not(:first-of-type), #observablehq-main h2:not(h1 + h2):has(a.observablehq-header-anchor)' is not a valid selector
    <anonymous> https://observablehq.com/framework/_observablehq/client.js:1
client.js:1
```

**Comment by mootari** [comment]
Looks like `:has()` requires FF 121 or higher: https://caniuse.com/css-has

([source](https://github.com/observablehq/framework/blob/f131567e0b61bc4b742604dee4c8f0409e42e1e8/src/render.ts#L154))

**Comment by Fil** [comment]
Yes, thanks for reporting. It was already discussed in #428, but it might still be possible to make it better than … crashing? In the meantime please update your browser ;-)
