### ISSUE TITLE
add java support to dataloaders

### ISSUE THREAD

**Issue by cyrilou242** [observablehq/framework#831]
Hey, 
It'd be nice to have support for java for dataloaders.

As of java 11 it's possible to run a java class directly with: 

```
java Test.java
```

so from what I understand it's only a matter of doing a PR similar to this one: 
https://github.com/observablehq/framework/pull/673/files

If you are ok I can do this for a first version. 

A second iteration would be to think of how dependencies are passed, but I haven't seen how this is done for other languages so maybe you don't want to allow this for the moment? 
A no dev way in java would be to pass it as an env var: 
```
export CLASSPATH=/some/dependencies.jar
```
other option is to pass it as an argument to the java command but this would be more involved. 

Thanks for the nice project!

**Comment by Fil** [comment]
Thanks, we welcome contributions.

Re: environments, we established a clear separation of concerns: setting up the env is _not_ the responsibility of Observable Framework. The `preview`, `build` (and `deploy`) commands only call the corresponding interpreter (or whatever is on the $PATH with that name), passing the loader script as argument. This works well in general for vanilla scripts. Anything beyond that, like requiring modules, extensions, etc, must be prepared in advance. (Of course there is an obvious escape hatch, in that a data loader can be a bash script that does all this work of setting up a venv.)

**Comment by cyrilou242** [comment]
Makes sense thanks. 
I'll try integrating and using java. Will create a PR when it's ready.
