### ISSUE TITLE
convert should read the config, and respect its output option

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#838]
#770 defaults `--output` to `.` It would be nicer to default to `docs/ `(or the `root` if specified in the config), so users can start preview/build faster without having to figure out this option.

**Comment by mbostock** [comment]
Retitled and redesigned: I think it should take the `--config` option (which defaults to `observablehq.config.{ts,js}` in the current working directory) and then respect the `output` option in the config, which defaults to `docs`. So if you have a different `output` set, `--output` will default to that. And maybe we don’t bother reading the config if you specify `--output` explicitly.
