### ISSUE TITLE
Getting started - Display Forecast gets Promise not Object

### ISSUE THREAD

**Issue by bertt** [observablehq/framework#856]
Hi, I'm following the getting started on WSL / Node v20.11.1 (https://observablehq.com/framework/getting-started) but get an Promise when doing the 'display(forecast)':

```
const forecast = FileAttachment("./data/forecast.json").json();
display(forecast);
```

![image](https://github.com/observablehq/framework/assets/538812/98c1c25a-7837-4f1a-85bb-2c136e3d768d)

Function 'node docs/data/forecast.json.js' works ok.

Any idea how to get the weather object showing up?

**Comment by Fil** [comment]
Maybe we should push https://github.com/observablehq/framework/pull/356 a bit further and make display await Promises.

````
```js
const forecast = FileAttachment("./data/forecast.json").json();
display(await forecast);
```
````

**Comment by bertt** [comment]
ah yes that works thanks

**Comment by bertt** [comment]
https://github.com/observablehq/framework/pull/857

**Comment by Fil** [comment]
Thanks for reporting this; since the copy says “another code block”, it's not technically wrong (not a bug). But there's room for improvement—either in the docs or in the way we display promises.
