### ISSUE TITLE
Tooltips in example histogram only show up when hovering over the left side of the bar

### ISSUE THREAD

**Issue by jaanli** [observablehq/framework#861]
This is super fun to try out, thank you!! 

I'm able to see the tooltips only when hovering over the left-hand side of a bar in the histogram; screenshot below.

Any tips on how to make the tooltips appear when moving the mouse over the center of a bar as well? 

Live demo: https://jaanli.github.io/american-community-survey/

The histogram code is here: https://github.com/jaanli/american-community-survey/blob/main/docs/components/apiHistogram.js which is taken from the example: https://github.com/observablehq/framework/blob/main/examples/api/docs/components/apiHistogram.js

The only changes to the example were:
* adding a `barWidth` parameter to make the bars easier to see: `const barWidth = 4;`
* changing `const ky = 165;` to `const ky = 6;` (number of points per pixel)
* changing `const dy = 500;` to `const dy = 300;` (number of rows)

<img width="286" alt="image" src="https://github.com/observablehq/framework/assets/5317244/67c3095b-e7cf-41bd-bda1-464e7eb011b3">

Another issue I have noticed is that the hover-over tooltip text with descriptions does not wrap the text and is cut off: 

<img width="281" alt="image" src="https://github.com/observablehq/framework/assets/5317244/cd420e34-5161-4d7a-bc83-f991ca8356e2">

**Comment by Fil** [comment]
The chart you're trying to adapt is not meant to be used with generic data. I'd suggest to use Plot instead (https://github.com/jaanli/american-community-survey/pull/1).

> the hover-over tooltip text with descriptions does not wrap the text and is cut off:

the tooltip is built with Plot.tip, which doesn't do line wrapping (yet); however you can control the line's width with the **lineWidth** option, which defaults to 20 (ems). See https://observablehq.com/plot/marks/tip#tip-mark

**Comment by jaanli** [comment]
Got it, thank you @Fil ! My bad, was just going off of the example -- will switch to Observable Plot now :) and try out the Mosaic example you shared too. Hopefully I can hack together some demos with AI soon! 🙏 🔥 🚒  you and your team rock!!!
