### ISSUE TITLE
draft mode

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#867]
A front matter option such as ~~`status: draft` or~~ `draft: true` makes a page visible in preview, but skipped during build.

The `--drafts` flag controls whether we build them or not (defaults to false for build and deploy, and true for preview).

drafts should not be indexed nor listed in the sidebar (unless set in pages).

**Comment by jaanli** [comment]
Agreed, right now I am just copying example markdown files to have an extension `.bak` so that they don't get built, then changing the extension back during development (to avoid committing the files as well).
