### ISSUE TITLE
Loading parquet file gives "RuntimeError: unreachable executed"

### ISSUE THREAD

**Issue by llimllib** [observablehq/framework#873]
As far as I can tell, the parquet file is valid; unfortunately I can't post the whole thing because it's derived from logs at work.

This is the code to try and load the file:

````markdown
```js echo
const stats = FileAttachment("log.parquet").parquet();
```

```js echo
display(Inputs.table(stats));
```
````

The full traceback from the console:

<details>

```
RuntimeError: unreachable executed
    RuntimeError http://127.0.0.1:3000/_observablehq/runtime.js:2
    value http://127.0.0.1:3000/_observablehq/runtime.js:2
    promise callback*mr http://127.0.0.1:3000/_observablehq/runtime.js:2
    wr http://127.0.0.1:3000/_observablehq/runtime.js:2
    value http://127.0.0.1:3000/_observablehq/runtime.js:2
    value http://127.0.0.1:3000/_observablehq/runtime.js:2
    promise callback*value http://127.0.0.1:3000/_observablehq/runtime.js:2
    value http://127.0.0.1:3000/_observablehq/runtime.js:2
    ar http://127.0.0.1:3000/_observablehq/runtime.js:2
    value http://127.0.0.1:3000/_observablehq/runtime.js:2
    onmessage http://127.0.0.1:3000/_observablehq/client.js:355
    onmessage http://127.0.0.1:3000/_observablehq/client.js:355
    open http://127.0.0.1:3000/_observablehq/client.js:285
    <anonymous> http://127.0.0.1:3000/logs:17
client.js:146:48
```

</details>

- The `parquet` CLI program reports that the file is normal: 
```
$ parquet check-stats log.parquet     
log.parquet has no corrupt stats
```
- `duckdb` can load the file without an issue:
<details>

```
D select * from 'log.parquet' order by timestamp desc limit 10;
100% ▕████████████████████████████████████████████████████████████▏ 
┌────────────────────────────────┬──────────────────────────┬──────────┐
│              path              │        timestamp         │ duration │
│            varchar             │         varchar          │  int64   │
├────────────────────────────────┼──────────────────────────┼──────────┤
│ /                              │ 2024-02-18T23:59:59.000Z │      138 │
│ /v1/request                    │ 2024-02-18T23:59:59.000Z │       94 │
│ /pageview                      │ 2024-02-18T23:59:59.000Z │      358 │
│ /v1/request                    │ 2024-02-18T23:59:59.000Z │       84 │
│ /wiz-docs/docs/getting-started │ 2024-02-18T23:59:59.000Z │     1622 │
│ /                              │ 2024-02-18T23:59:59.000Z │      120 │
│ /                              │ 2024-02-18T23:59:59.000Z │      161 │
│ /                              │ 2024-02-18T23:59:59.000Z │      101 │
│ /                              │ 2024-02-18T23:59:59.000Z │      242 │
│ /                              │ 2024-02-18T23:59:59.000Z │      180 │
├────────────────────────────────┴──────────────────────────┴──────────┤
│ 10 rows                                                    3 columns │
└──────────────────────────────────────────────────────────────────────┘
D create table logs as select * from 'log.parquet';
100% ▕████████████████████████████████████████████████████████████▏ 
D select max(duration) from logs;
┌───────────────┐
│ max(duration) │
│     int64     │
├───────────────┤
│        461646 │
└───────────────┘
```

</details>

The file is large: 270mb. Is that just too big for javascript in my browser? Any further way I can debug what's going on here?

**Comment by Fil** [comment]
Can you try to create a fake dataset that reproduces the bug? Maybe by setting all fields to random gibberish? Otherwise this issue is not actionable.

**Comment by espinielli** [comment]
I am curious too to see a reproducible example.
I tried to output a simple dataset in parquet in R but failed miserably...I haven't been able to find any docs/examples that make it possible to spit to stdout.
My naive reproducible example for a `log.parquet.R` data loader would have been:

```r
library(dplyr)
library(arrow)

tribble(
  ~colA, ~colB,
  "a",   1,
  "b",   2
  "c",   3
) |> 
  write_parquet(stdout())
```
but it failed with
```text
Error in seek.connection(1L) : 'seek' not enabled for this connection
Error in close.connection(1L) : cannot close standard connections
```

**Comment by Fil** [comment]
@espinielli it looks like write_parquet expects to write to disk, not to stdout which doesn't allow arbitrary seeks. So you might want to write to a temp file on disk, then cat the temp file to stdout.

**Comment by espinielli** [comment]
@Fil yes that is what I will try:
1. Write to a temporary file
2. Dump to stdout

**Comment by Fil** [comment]
@espinielli for inspiration you can take a look at @allisonhorst's (work in progress) R data loader at https://github.com/observablehq/framework/pull/749/files#diff-2ef0831543dc2337a63f37ab4e629cc287b3e09b9ba63cabf788d09b29536bda

**Comment by llimllib** [comment]
Unfortunately the [arrow wasm library says](https://github.com/kylebarron/parquet-wasm/tree/d3c62e4e45775b0c0238ad093748a3f698a0a750?tab=readme-ov-file#debug-functions) that there's a function to print a useful error message, but that it's disabled to reduce bundle size.

I'm still trying to narrow this down... I have generated a log file of similar size & composition that works, but I get this error reproducibly on my own file.

**Comment by Fil** [comment]
I have an example where the errors I get (with duckdb-wasm) are:
> RuntimeError: Invalid Error: don't know what type: 

and
> RuntimeError: Invalid Error: Variable-length int over 10 bytes.

From this repo, we can only hope that the duckdb/parquet/arrow tooling becomes better. But it might help to open a relevant issue with them once we close in on what causes it.

**Comment by mrppdex** [comment]
I came across RuntimeError: unreachable executed message. I'm not sure why transforming my data to `df <- df[1:nrow(df),]` helped, but it did.

```R
library(arrow)
library(clinicalfd)

df <- clinicalfd::adsl
df <- df[1:nrow(df),]

# Write the data frame to a temporary Parquet file
temp_file <- tempfile(fileext = ".parquet")
arrow::write_parquet(df, sink = temp_file)

system2('/bin/cat', args = temp_file)
```

**Comment by espinielli** [comment]
In an interactive session `df <- clinicalfd::adsl` resolves directly to a data frame.
My guess is that in a non interactive session you instead get a `Promise` which is not yet resolved when you save the parquet file.
Probably substituting 
```r
df <- df[1:nrow(df),]
```
with
```r
rlang::eval_tidy(df)
```
would do...

Anyway, I would access the data from a package with `utils::data()` so your code would be

```r
# you need to have installed `rlang` (and `sas2r/clinical_fd`)
library(arrow)

utils::data(adsl, package = "clinicalfd")   # you get `adsl` as a Promise object
rlang::eval_tidy(adsl)                      # resolve the Promise, now `adsl` is a data frame

# Write the data frame to a temporary Parquet file
temp_file <- tempfile(fileext = ".parquet")
arrow::write_parquet(adsl, sink = temp_file)

system2('/bin/cat', args = temp_file)
```

**Comment by mrppdex** [comment]
I tried both
```R
rlang::eval_tidy(df)
# AND
force(df)
```
And it didn't help. I ran `all_equal(df, df[1:nrow(df),]` and there are differences in attributes between both data frames. Original has attribute 'label' associated with column names, and transformed has them stripped off.

**ORIGINAL**
` $ mmsetot : 'labelled' int  23 23 23 23 21 23 10 23 20 20 ...
  ..- attr(*, "label")= chr "MMSE Total"`

**TRANSFORMED**
`$ mmsetot : int  23 23 23 23 21 23 10 23 20 20 ...`

It looks like there's an issue with loading parquet data with labelled column names.

**Comment by llimllib** [comment]
@mrppdex you may want to [file an issue on the parquet-wasm repo](https://github.com/kylebarron/parquet-wasm/issues) if you have a parquet file that reproducibly causes the issue
