### ISSUE TITLE
'copied' information badge

### ISSUE THREAD

**Issue by imhalid** [observablehq/framework#877]
What do you think about adding a small notification to the copy button to improve the user experience?

I prepared a small demo for this. You can see it in the videos below.

#### Without Badge 

https://github.com/observablehq/framework/assets/40598819/679e37a0-3120-4ec9-a047-04212bab57d3

#### With Badge

https://github.com/observablehq/framework/assets/40598819/961e474c-b72b-4e56-96d6-0ffb5603a23e

**Comment by mbostock** [comment]
Fixed in #893. Thank you!
