### ISSUE TITLE
Support for Julia data loader

### ISSUE THREAD

**Issue by vnegi10** [observablehq/framework#898]
Although the [Data loaders](https://observablehq.com/framework/loaders) page shows a small Julia example, support for Julia does not seem to be implemented. I keep getting `RuntimeError: Unable to load file` error on the dashboard.

I think updating `src/dataloader.ts` should be enough. Please let me know if the [linked PR](https://github.com/observablehq/framework/pull/899) needs any further changes.

Thank you for all the hard work and looking forward to using Julia as the back-end!

**Comment by Fil** [comment]
The julia example in the documentation is supposed to show how to use _any_ language (even those we haven't included), thanks to a shebang (`#!/usr/bin/env julia`) and a `.exe` extension. But apparently it misses the point?
