### ISSUE TITLE
Descenders in H1 may be cut-off in the default template’s index page

### ISSUE THREAD

**Issue by mootari** [observablehq/framework#904]
The default ~~theme~~ template index page specifies a line height of ~~1em~~ 1 for the h1 title, causing descenders on the last line in some fonts like Arial Black to get cut off.

<img width="1056" alt="image" src="https://github.com/observablehq/framework/assets/322014/df2b09fc-9e7b-4a7f-ad21-c603beeed7be">

**Comment by mbostock** [comment]
Is this caused by the `background-clip: text`? It shouldn’t normally matter that the `line-height: 1` doesn’t fit the descenders. Also, this isn’t the default theme; it’s simply the index page on the default template.

**Comment by mbostock** [comment]
Not planning on fixing this.
