### ISSUE TITLE
Requestion: Something like DOM.Download

### ISSUE THREAD

**Issue by palewire** [observablehq/framework#906]
I'd love to see something like [this](https://github.com/observablehq/stdlib?tab=readme-ov-file#DOM_download) in the Inputs library of framework.

**Comment by Fil** [comment]
Note that it's already possible to copy the code into a file (say, `components/download.js`), then call

````md
```js
import {download} from "./components/download.js";
```
````

(It's what I do for Promises.delay, for example.)

**Comment by mbostock** [comment]
Duplicate of #869.
