### ISSUE TITLE
Optionally emit page links with “.html” for static file servers that don’t support implicit extensions when routing

### ISSUE THREAD

**Issue by pettiross** [observablehq/framework#92]
I copied my `dist` folder to a basic web server. The index file loaded, but the links to pages like Observable GitHub fail to load because the URL specified was just to `/github` instead of `/github.html`.

**Comment by nelreina** [comment]
> There should definitely be an option for emitting `.html`, and I think perhaps even this should be the default behavior because it works universally. Even `http-server` doesn’t handle serving `/javascript` correctly, for example. #171

This will be handy spacially when want to run in docker with minimal storage footprint. E.g. busybox httpd server is lika < 10mb . Nginx static is like 40mb / if I use node then it will be 260+ MB
