### ISSUE TITLE
Server-Side Rendering (SSR)

### ISSUE THREAD

**Issue by jheer** [observablehq/framework#931]
Thanks for the great work on Framework!

For even faster (perceived) page loads it would be valuable to render initial views of charts and other content on the server, then "hydrate" them on the client once corresponding runtime cells are ready. For example, I'd like to publish static SVG as part of the initial page content, which can then be replaced with "live" content upon load.

I realize there be dragons here, especially with arbitrary code that may involve randomness, generators, or otherwise cause strange changes of content upon hydration, and so on. Nevertheless, I see a lot of value in being able to knowingly _opt-in_ to SSR.

I imagine one would have to instantiate a runtime during server-side compilation then extract resulting content. We do something similar in [Living Papers](https://github.com/uwdata/living-papers/blob/main/packages/compiler/src/transforms/convert/convert-component.js) using Puppeteer to extract and screenshot runtime-generated content, though a lighter weight approach (e.g., using jsdom and node canvas?) may be preferable and cover common use cases.

It looks like [some work in this direction](https://github.com/observablehq/framework/pull/413) is ongoing, though I'm not sure of the planned scope. So, just wanted to share a plug for this!

**Comment by mbostock** [comment]
Related #234 #141.

**Comment by Fil** [comment]
As a complement/alternative/easy first step, I would like to think about registering cell dimensions #933.

**Comment by jaanli** [comment]
Agreed! This would support very cool use cases, added a discussion as well:

https://github.com/observablehq/framework/discussions/855

**Comment by Fil** [comment]
Maybe we should reopen this issue, which is mentioned in https://github.com/observablehq/framework/blob/fa804894d0de62dd710e5c1b7630df2ded2d9e13/docs/jsx.md?plain=1#L114 and not completely completed? Or open a new one with new goals (SSR code blocks, hydration…).

**Comment by mbostock** [comment]
We have #234 #145 already so let’s keep this closed. We could open up another issue for JSX hydration.
