### ISSUE TITLE
Support footnotes in markdown text

### ISSUE THREAD

**Issue by tgy** [observablehq/framework#940]
Notebooks often need to omit details in the main text, but these details still need to be there somewhere. Footnotes are a perfect way to achieve this.

[markdown-it](https://github.com/markdown-it/markdown-it) does support footnotes. What's stopping us from having them in our Observable Framework notebooks? :)

Bonus point would be to have the possibility to have the footnotes on the right side of the notebook, or have them appear on mouseOver.

**Comment by tgy** [comment]
@Fil yes exactly!

**Comment by mbostock** [comment]
Maybe we could have a way to register markdown-it plugins in the config file?

**Comment by huw** [comment]
:+1: to custom `markdown-it` plugins, that would make supporting [Wikilinks](https://help.obsidian.md/Linking+notes+and+files/Internal+links) a lot easier

**Comment by Fil** [comment]
After #965 you can install the `markdown-it-footnote` manually, and tweak the styles to make it look good. We're also reporting good results with `markdown-it-container`.

**Comment by mbostock** [comment]
Live example: https://observablehq.observablehq.cloud/framework-example-markdown-it-footnote/

**Comment by Fil** [comment]
I thought maybe something was missing… the emoji arrows don't look too good, do they?

**Comment by tgy** [comment]
Which emoji arrows? This is what I have 
![image](https://github.com/observablehq/framework/assets/694873/430f2be9-57a0-43bb-bc45-8c340bcb9083)

**Comment by mbostock** [comment]
It looks fine in macOS Safari, but in Chrome it renders as:

<img width="225" alt="Screenshot 2024-06-09 at 2 04 03 PM" src="https://github.com/observablehq/framework/assets/230541/3f9dad87-f573-4f6f-8f4e-e95d4ac9ffee">

One probably needs to use the [VS15 variation selector](https://codepoints.net/U+FE0E?lang=en) to prevent emoji presentation. I assume that’s an option with the markdown-it-footnote plugin?
