### ISSUE TITLE
build index.html in all subfolders: _file, _observablehq etc.?

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#951]
Some web hosts default to directory listing, which we could prevent pro-actively by creating a simple `index.html` file that just contains a link to the home page. In particular I wouldn't want `_file/` to be listable.

**Comment by mbostock** [comment]
What are some examples of web hosts that support directory listing? That seems like a generally insecure practice. It would be tedious to create an index.html not just for the top-level `_file`, `_import`, `_observablehq` etc. but for all subdirectories within.

**Comment by Fil** [comment]
I don't have an example in mind. I saw Vercel supports it as an option (though it's off by default), and thought about this issue. Maybe it's not as common as it used to be. Re: tediousness, I was thinking that the action could be part of prepareOutput.
