### ISSUE TITLE
1.1.x: FileAttachment path resolution in components not working

### ISSUE THREAD

**Issue by hrbrmstr** [observablehq/framework#989]
In 1.0.0, I have this project structure (reproducible example: https://github.com/hrbrmstr/file-attachment-issue-1.1.x):

```ini
.
├── docs
│   ├── components
│   │   └── kev-utils.js
│   ├── data
│   │   └── cisa-kev.json.sh
│   └── index.md
├── observablehq.config.ts
└── package.json
```

and in `kev-utils.js` I have this:

```js
import { FileAttachment } from "npm:@observablehq/stdlib";

export const kev = await FileAttachment("/data/cisa-kev.json").json();
```

and this in `index.md`:

```markdown
```js
import { kev } from './components/kev-utils.js';

view(kev)
```

it would [work](https://kev.hrbrmstr.app/) ([code](https://codeberg.org/hrbrmstr/kev-report/src/branch/batman/docs/components/kev-utils.js))

Now, it does not.  (in `dev` or `build`)

`build` definitely sees the `FileAttachment`:

```plain
(node:97565) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
found 1 page in docs
parse docs/index.md in 41ms
build node_modules/@observablehq/framework/dist/client/index.js → dist/_observablehq/client.js
build node_modules/@observablehq/framework/dist/client/runtime.js → dist/_observablehq/runtime.js
build node_modules/@observablehq/framework/dist/client/stdlib.js → dist/_observablehq/stdlib.js
build observablehq:theme-air,near-midnight.css → dist/_observablehq/theme-air,near-midnight.css
load docs/data/cisa-kev.json.sh → [fresh] success 674.39 KiB in 0ms
copy docs/.observablehq/cache/data/cisa-kev.json → dist/_file/data/cisa-kev.adfadf26.json
copy docs/components/kev-utils.js → dist/_import/components/kev-utils.3898a0c9.js
render docs/index.md → dist/index.html
```

I've tried modifying the path

- `data/   => http://localhost:3000/_import/components/_file/components/data/cisa-kev.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
- `/data/  => http://localhost:3000/_import/components/_file/data/cisa-kev.json?sha=221b835b619506dbf4b5dd69d42254579fcac76ad6d3ff0fd8bbcf8a3fe4d5f6`
- `./data/ => http://localhost:3000/_import/components/_file/components/data/cisa-kev.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

and it doesn't work.

It works fine if the `FileAttachment` is in the `md`.

Is the thinking that no data wrangling should be happening in the dashboard and that components are just receivers of data?

**Comment by Fil** [comment]
Is the repro complete? I have tried to downgrade https://github.com/hrbrmstr/file-attachment-issue-1.1.x/blob/batman/package.json to framework: "1.0.0", and the data still didn't load.

**Comment by mbostock** [comment]
This looks valid to me. I will investigate shortly.

**Comment by armin77** [comment]
Got kind of the same issue trying to `npm update` framework to v1.1.2 (macOS v12.7.1)
(Browser-console reads: SyntaxError: Importing binding name 'FileAttachments' is not found.)
Downgrading to 1.0.0 solved it for me! and as usual `rm -rf node_modules` before reinstalling

**Comment by mbostock** [comment]
Confirmed that there’s a bug with resolution of `FileAttachment` within imported modules. My apologies. We’ll get this sorted today.
